"""Authoritative roster and tailored content for the 32 ASFE specialist SKILLS.

Each entry follows the Master Skills Library roster. Lists are intentionally
role-specific so the generated handbooks are substantive rather than generic.
Fields omitted by an entry fall back to sensible cross-cutting defaults in the
generator.
"""

# name, dept(folder code), reports_to, collaborators, criticality, tags
SKILLS = [
    {
        "name": "Backend_Engineer", "dept": "05_Backend", "reports_to": "Principal Engineer",
        "collaborators": ["API Architect", "Database Architect", "Security Engineer", "DevOps Engineer", "QA Engineer"],
        "criticality": "High", "tags": ["backend", "api", "security"],
        "mission": "Design, build, and operate reliable, secure, observable backend services that implement product capabilities behind well-defined API contracts.",
        "responsibilities": [
            "Implement business logic as cohesive, testable services with clear boundaries.",
            "Own service-level reliability: idempotency, retries, timeouts, and graceful degradation.",
            "Design data access patterns in partnership with the Database Architect.",
            "Enforce authentication, authorization, and input validation on every endpoint.",
            "Instrument services with structured logs, metrics, and distributed traces.",
            "Write unit, integration, and contract tests to protect behaviour.",
            "Manage schema and API backward compatibility across releases.",
            "Participate in on-call and resolve production incidents within SLOs.",
        ],
        "scope": [
            "Server-side application code and domain logic",
            "Service-to-service and service-to-datastore integration",
            "Background jobs, queues, and scheduled tasks",
            "Endpoint-level security controls and validation",
        ],
        "out_of_scope": [
            "Client-side rendering and UI styling (Frontend Engineer)",
            "Cloud network topology and account guardrails (Cloud Architect)",
            "Canonical API contract ownership (API Architect)",
        ],
        "primary": [
            "Deliver correct, secure, performant service behaviour behind stable contracts.",
            "Keep error budgets healthy and meet latency/availability SLOs.",
        ],
        "deliverables": [
            "Service implementations with tests and runbooks",
            "API handlers conforming to the OpenAPI contract",
            "Migration-safe data access code",
            "Dashboards and alerts for owned services",
        ],
        "best_practices": [
            "Validate and normalise all inputs at the boundary; never trust callers.",
            "Make write operations idempotent and safe to retry.",
            "Use parameterised queries and an ORM/repository layer to prevent injection.",
            "Apply timeouts, circuit breakers, and bulkheads to external calls.",
            "Prefer stateless services; externalise state to datastores and caches.",
            "Return RFC 9457 problem-details for errors; never leak internals.",
        ],
        "anti_patterns": [
            "Business logic embedded in controllers or database triggers.",
            "Unbounded queries or N+1 access patterns under load.",
            "Catch-and-ignore error handling that hides failures.",
            "Storing secrets in code or environment files committed to VCS.",
            "Breaking API changes shipped without versioning or deprecation.",
        ],
        "kpis": [
            "p99 latency within SLO", "Availability (>= 99.9%)", "Error budget burn rate",
            "Change failure rate", "Test coverage of critical paths", "Mean time to recovery (MTTR)",
        ],
    },
    {
        "name": "Frontend_Engineer", "dept": "04_Frontend", "reports_to": "Principal Engineer",
        "collaborators": ["UI/UX Designer", "Accessibility Specialist", "Backend Engineer", "Performance Engineer", "QA Engineer"],
        "criticality": "High", "tags": ["frontend", "accessibility", "performance"],
        "mission": "Build accessible, fast, and maintainable client applications that faithfully implement designs and consume APIs safely.",
        "responsibilities": [
            "Implement UI components against the design system and tokens.",
            "Meet WCAG 2.2 AA accessibility requirements in every view.",
            "Optimise Core Web Vitals (LCP, INP, CLS) within performance budgets.",
            "Manage client state predictably and handle async/error states.",
            "Consume APIs defensively with validation and graceful failure.",
            "Write component, integration, and end-to-end tests.",
            "Prevent XSS and unsafe rendering of untrusted content.",
            "Ensure responsive, internationalised, and themeable UI.",
        ],
        "scope": [
            "Client application code and component library usage",
            "Accessibility and responsive behaviour of the UI",
            "Client-side performance and bundle budgets",
            "Front-end API integration and error handling",
        ],
        "out_of_scope": [
            "Server-side business logic (Backend Engineer)",
            "Visual design and tokens authorship (UI/UX Designer)",
            "API contract definition (API Architect)",
        ],
        "primary": [
            "Ship accessible, performant interfaces that match approved designs.",
            "Keep bundle size and Core Web Vitals within agreed budgets.",
        ],
        "deliverables": [
            "Accessible, tested UI components and pages",
            "Storybook/usage docs for shared components",
            "Performance and a11y test results",
            "Client error and event instrumentation",
        ],
        "best_practices": [
            "Use semantic HTML first; add ARIA only when necessary.",
            "Render untrusted data as text; sanitise any HTML.",
            "Code-split and lazy-load to protect the critical path.",
            "Make all interactive elements keyboard operable with visible focus.",
            "Treat all API responses as untrusted and validate shapes.",
        ],
        "anti_patterns": [
            "Div-soup with click handlers instead of semantic controls.",
            "Blocking the main thread with heavy synchronous work.",
            "Storing tokens in localStorage without considering XSS risk.",
            "Shipping images without dimensions, causing layout shift.",
        ],
        "kpis": [
            "LCP / INP / CLS within budget", "Accessibility violations (axe) = 0 critical",
            "JS bundle size budget adherence", "Client error rate", "Component test coverage",
        ],
    },
    {
        "name": "Database_Architect", "dept": "09_Database", "reports_to": "Principal Engineer",
        "collaborators": ["Backend Engineer", "Data Engineer", "Security Engineer", "Performance Engineer", "Privacy Engineer"],
        "criticality": "Critical", "tags": ["data", "backend", "security"],
        "mission": "Design durable, performant, and secure data models and ensure safe evolution of schemas across the product lifecycle.",
        "responsibilities": [
            "Design normalised, well-indexed schemas fit for access patterns.",
            "Define and review migrations for zero-downtime deployment.",
            "Establish backup, restore, and point-in-time recovery procedures.",
            "Set retention, archival, and partitioning strategies.",
            "Enforce encryption at rest and least-privilege data access.",
            "Tune queries and indexes against real workloads.",
            "Classify and protect sensitive/PII columns with Privacy.",
        ],
        "scope": [
            "Logical and physical data models",
            "Schema migrations and versioning",
            "Indexing, partitioning, and query performance",
            "Backup, recovery, and retention policy",
        ],
        "out_of_scope": [
            "Application business logic (Backend Engineer)",
            "Analytics warehouse modelling (Data Engineer)",
        ],
        "primary": [
            "Guarantee data integrity, durability, and recoverability.",
            "Enable safe, reversible schema evolution.",
        ],
        "deliverables": [
            "Entity-relationship models and data dictionaries",
            "Reviewed, reversible migration scripts",
            "Backup/restore runbooks with tested RPO/RTO",
            "Index and capacity recommendations",
        ],
        "best_practices": [
            "Make migrations additive and reversible; expand-then-contract.",
            "Index for the queries you run, not speculatively.",
            "Encrypt at rest and restrict access by role and column.",
            "Test restores regularly; an untested backup is not a backup.",
        ],
        "anti_patterns": [
            "Destructive migrations without a rollback path.",
            "Storing PII without classification or encryption.",
            "Premature denormalisation that corrupts integrity.",
        ],
        "kpis": [
            "Query p99 within SLO", "Successful restore drills", "Migration rollback rate",
            "Replication lag", "Storage growth vs. forecast",
        ],
    },
    {
        "name": "API_Architect", "dept": "10_API", "reports_to": "Enterprise Architect",
        "collaborators": ["Backend Engineer", "Frontend Engineer", "Security Engineer", "Technical Writer", "Product Manager"],
        "criticality": "Critical", "tags": ["api", "backend", "security"],
        "mission": "Own the canonical API contracts, versioning strategy, and governance that keep integrations stable and secure.",
        "responsibilities": [
            "Author and review OpenAPI/AsyncAPI contracts as the source of truth.",
            "Define versioning, deprecation, and backward-compatibility policy.",
            "Standardise pagination, filtering, errors, and idempotency.",
            "Govern authentication, authorization, and rate-limiting patterns.",
            "Ensure contracts are testable and consumer-driven.",
        ],
        "scope": [
            "API contracts and design standards",
            "Versioning and deprecation governance",
            "Error model and pagination conventions",
        ],
        "out_of_scope": [
            "Endpoint implementation (Backend Engineer)",
            "Infrastructure provisioning (Cloud Architect)",
        ],
        "primary": [
            "Provide stable, consistent, well-documented contracts.",
            "Prevent breaking changes from reaching consumers unannounced.",
        ],
        "deliverables": [
            "Versioned OpenAPI/AsyncAPI specifications",
            "API style guide and error catalogue",
            "Deprecation timelines and migration guides",
        ],
        "best_practices": [
            "Design contracts first; generate code and docs from them.",
            "Use RFC 9457 problem-details for a consistent error model.",
            "Version explicitly; never repurpose existing fields.",
            "Make every mutating endpoint idempotent where feasible.",
        ],
        "anti_patterns": [
            "Leaking internal models directly as API responses.",
            "Silent breaking changes to shapes or semantics.",
            "Inconsistent pagination/error conventions across endpoints.",
        ],
        "kpis": [
            "Contract test pass rate", "Breaking-change incidents", "Spec-to-docs freshness",
            "Adoption of latest version", "Mean deprecation lead time",
        ],
    },
    {
        "name": "Cloud_Architect", "dept": "11_Cloud", "reports_to": "Enterprise Architect",
        "collaborators": ["DevOps Engineer", "Security Engineer", "SRE", "Finance", "Backend Engineer"],
        "criticality": "Critical", "tags": ["cloud", "security", "observability"],
        "mission": "Design secure, resilient, cost-aware cloud foundations aligned to well-architected principles.",
        "responsibilities": [
            "Design network topology, identity, and account/project guardrails.",
            "Define multi-AZ/region resilience and disaster-recovery posture.",
            "Establish landing zones, tagging, and cost governance.",
            "Codify infrastructure with IaC and policy-as-code.",
            "Set encryption, key management, and secrets baselines.",
        ],
        "scope": [
            "Cloud accounts, networking, and identity",
            "Resilience, DR, and capacity strategy",
            "Cost governance and tagging",
        ],
        "out_of_scope": [
            "Application code (Backend/Frontend Engineers)",
            "Pipeline tooling specifics (DevOps Engineer)",
        ],
        "primary": [
            "Provide a secure, resilient, cost-efficient platform.",
            "Eliminate configuration drift via IaC and policy.",
        ],
        "deliverables": [
            "Landing-zone and network reference architectures",
            "IaC modules and policy-as-code guardrails",
            "DR plan with tested RPO/RTO",
        ],
        "best_practices": [
            "Default to least privilege and private networking.",
            "Encrypt everywhere; manage keys centrally.",
            "Make infrastructure reproducible and immutable.",
            "Tag everything for cost and ownership attribution.",
        ],
        "anti_patterns": [
            "Click-ops changes that bypass IaC.",
            "Wildcard IAM permissions and public-by-default storage.",
            "Single-AZ critical systems without DR.",
        ],
        "kpis": [
            "Infrastructure drift incidents", "DR drill success", "Cloud cost variance vs. budget",
            "Policy compliance rate", "Recovery time objective attainment",
        ],
    },
    {
        "name": "DevOps_Engineer", "dept": "12_DevOps", "reports_to": "Engineering Manager",
        "collaborators": ["Cloud Architect", "DevSecOps Engineer", "Backend Engineer", "SRE", "Release Manager"],
        "criticality": "High", "tags": ["cloud", "release", "observability"],
        "mission": "Automate build, test, and deployment pipelines for fast, safe, repeatable delivery.",
        "responsibilities": [
            "Build and maintain CI/CD pipelines with quality gates.",
            "Automate environment provisioning via IaC.",
            "Implement progressive delivery (canary, blue/green).",
            "Manage artifacts, versioning, and supply-chain integrity.",
            "Automate rollback and release verification.",
        ],
        "scope": [
            "CI/CD pipeline definition and tooling",
            "Build, artifact, and environment automation",
            "Deployment strategy and rollback automation",
        ],
        "out_of_scope": [
            "Application feature code", "Cloud account guardrail ownership (Cloud Architect)",
        ],
        "primary": [
            "Make deployments boring, fast, and reversible.",
            "Embed automated quality and security gates in the pipeline.",
        ],
        "deliverables": [
            "Reusable pipeline templates",
            "IaC environment definitions",
            "Automated rollback and smoke-test stages",
        ],
        "best_practices": [
            "Build once, promote the same artifact across environments.",
            "Gate releases on tests, scans, and policy checks.",
            "Sign artifacts and generate SBOMs for the supply chain.",
            "Automate rollback as a first-class, tested path.",
        ],
        "anti_patterns": [
            "Manual deployment steps and snowflake environments.",
            "Skipping gates under deadline pressure.",
            "Storing credentials in pipeline config.",
        ],
        "kpis": [
            "Deployment frequency", "Lead time for changes", "Change failure rate",
            "MTTR", "Pipeline duration", "Rollback success rate",
        ],
    },
    {
        "name": "DevSecOps_Engineer", "dept": "13_DevSecOps", "reports_to": "Security Architect",
        "collaborators": ["Security Engineer", "DevOps Engineer", "Cloud Architect", "Compliance Specialist"],
        "criticality": "Critical", "tags": ["security", "cloud", "compliance"],
        "mission": "Embed automated security across the SDLC so vulnerabilities are caught early and continuously.",
        "responsibilities": [
            "Integrate SAST, DAST, SCA, secret, and IaC scanning into pipelines.",
            "Define and enforce security gates and policy-as-code.",
            "Manage vulnerability triage and remediation SLAs.",
            "Maintain SBOMs and supply-chain attestations.",
            "Automate compliance evidence collection.",
        ],
        "scope": [
            "Pipeline security tooling and gates",
            "Vulnerability management and SLAs",
            "Supply-chain integrity and SBOMs",
        ],
        "out_of_scope": [
            "Threat modelling ownership (Security Engineer)",
            "Legal interpretation of regulations (Legal/Compliance)",
        ],
        "primary": [
            "Shift security left with automated, enforced controls.",
            "Reduce mean time to remediate vulnerabilities.",
        ],
        "deliverables": [
            "Security pipeline stages and policies",
            "Vulnerability dashboards and SLAs",
            "SBOMs and supply-chain attestations",
        ],
        "best_practices": [
            "Fail builds on critical findings; track exceptions formally.",
            "Scan dependencies and containers continuously.",
            "Treat infrastructure code as a security-reviewed artifact.",
        ],
        "anti_patterns": [
            "Security scans that only run manually or post-release.",
            "Unbounded exception lists with no expiry.",
            "Ignoring transitive dependency risk.",
        ],
        "kpis": [
            "Mean time to remediate (MTTR) by severity", "Critical findings in production",
            "Scan coverage", "Exception backlog age", "SBOM coverage",
        ],
    },
    {
        "name": "Site_Reliability_Engineer", "dept": "27_Operations", "reports_to": "Head of Operations",
        "collaborators": ["Observability Engineer", "Backend Engineer", "Cloud Architect", "DevOps Engineer"],
        "criticality": "Critical", "tags": ["observability", "cloud", "release"],
        "mission": "Keep production reliable through SLOs, error budgets, capacity planning, and disciplined incident response.",
        "responsibilities": [
            "Define SLIs/SLOs and manage error budgets with product.",
            "Lead incident response and blameless postmortems.",
            "Plan capacity and conduct load/chaos testing.",
            "Reduce toil through automation.",
            "Own production readiness reviews.",
        ],
        "scope": [
            "Reliability targets and error budgets",
            "Incident command and postmortems",
            "Capacity and resilience engineering",
        ],
        "out_of_scope": [
            "Feature development", "Telemetry instrumentation authorship (Observability Engineer)",
        ],
        "primary": [
            "Meet reliability targets within error budgets.",
            "Continuously reduce toil and incident recurrence.",
        ],
        "deliverables": [
            "SLO definitions and error-budget policy",
            "Incident postmortems with actions",
            "Capacity plans and chaos results",
        ],
        "best_practices": [
            "Tie release velocity to error-budget health.",
            "Run blameless postmortems with tracked actions.",
            "Automate repetitive operational work.",
        ],
        "anti_patterns": [
            "Alerting on causes instead of symptoms.",
            "Postmortems without owned, time-bound actions.",
            "Ignoring error-budget exhaustion.",
        ],
        "kpis": [
            "SLO attainment", "Error-budget burn", "MTTR", "Incident recurrence rate", "Toil percentage",
        ],
    },
    {
        "name": "Observability_Engineer", "dept": "19_Observability", "reports_to": "Head of Operations",
        "collaborators": ["SRE", "Backend Engineer", "DevOps Engineer", "Performance Engineer"],
        "criticality": "High", "tags": ["observability", "performance"],
        "mission": "Provide unified, high-signal telemetry (logs, metrics, traces) enabling fast detection and diagnosis.",
        "responsibilities": [
            "Standardise instrumentation with OpenTelemetry.",
            "Build dashboards aligned to SLIs and user journeys.",
            "Design actionable, low-noise alerting.",
            "Manage telemetry cost, retention, and cardinality.",
            "Enable distributed tracing across services.",
        ],
        "scope": [
            "Telemetry standards and pipelines",
            "Dashboards, alerts, and SLIs",
            "Trace propagation and correlation",
        ],
        "out_of_scope": ["SLO ownership (SRE)", "Feature code"],
        "primary": [
            "Make every production issue observable and diagnosable quickly.",
            "Keep alerts actionable and noise low.",
        ],
        "deliverables": [
            "OpenTelemetry instrumentation standards",
            "Service and journey dashboards",
            "Alert rules with runbooks",
        ],
        "best_practices": [
            "Use structured, correlated logs with trace IDs.",
            "Alert on symptoms tied to SLOs, not raw causes.",
            "Control cardinality to manage cost and performance.",
        ],
        "anti_patterns": [
            "Log spam without structure or correlation.",
            "Dashboards nobody uses; alerts everyone ignores.",
            "Unbounded label cardinality.",
        ],
        "kpis": [
            "Mean time to detect (MTTD)", "Alert precision/recall", "Trace coverage",
            "Telemetry cost per service", "Dashboard usage",
        ],
    },
    {
        "name": "AI_Engineer", "dept": "06_AI", "reports_to": "AI Engineering Director",
        "collaborators": ["Prompt Engineer", "RAG Engineer", "AI Safety Engineer", "AI Evaluation Engineer", "Backend Engineer"],
        "criticality": "Critical", "tags": ["ai", "security", "eval"],
        "mission": "Design and operate production LLM/AI features that are accurate, safe, observable, and cost-effective.",
        "responsibilities": [
            "Architect AI features, model selection, and orchestration.",
            "Integrate models via gateways with fallback and routing.",
            "Implement guardrails, validation, and output schemas.",
            "Instrument quality, latency, and cost telemetry.",
            "Manage prompt/version lifecycle with evaluation gates.",
            "Apply MCP and tool-calling patterns safely.",
        ],
        "scope": [
            "AI feature architecture and orchestration",
            "Model integration, routing, and fallback",
            "Guardrails, output validation, and cost control",
        ],
        "out_of_scope": [
            "Prompt copywriting at scale (Prompt Engineer)",
            "Retrieval pipeline internals (RAG Engineer)",
        ],
        "primary": [
            "Ship AI features that meet quality, safety, latency, and cost targets.",
            "Make AI behaviour measurable and regression-tested.",
        ],
        "deliverables": [
            "AI feature architecture and orchestration code",
            "Guardrail and output-validation layers",
            "AI telemetry dashboards (quality/latency/cost)",
        ],
        "best_practices": [
            "Constrain outputs with schemas and validate before use.",
            "Treat prompts as versioned, evaluated artifacts.",
            "Add fallbacks and timeouts around model calls.",
            "Never send secrets/PII to models without controls.",
        ],
        "anti_patterns": [
            "Unbounded prompt injection of untrusted content.",
            "No evaluation gate before prompt/model changes.",
            "Trusting model output as executable without validation.",
        ],
        "kpis": [
            "Answer quality/eval score", "Hallucination rate", "p95 latency",
            "Cost per request", "Guardrail block rate", "Eval regression catch rate",
        ],
    },
    {
        "name": "Prompt_Engineer", "dept": "06_AI", "reports_to": "AI Engineering Director",
        "collaborators": ["AI Engineer", "AI Evaluation Engineer", "RAG Engineer", "Product Manager"],
        "criticality": "High", "tags": ["ai", "eval"],
        "mission": "Design, version, and evaluate prompts and instructions that produce reliable, safe, on-spec model behaviour.",
        "responsibilities": [
            "Author and maintain versioned prompt templates.",
            "Define output schemas and few-shot exemplars.",
            "Build evaluation suites for prompt changes.",
            "Mitigate prompt-injection and jailbreaks.",
            "Optimise token cost and latency.",
        ],
        "scope": ["Prompt templates and instructions", "Prompt evaluation and versioning", "Injection mitigation"],
        "out_of_scope": ["Model hosting/integration (AI Engineer)", "Retrieval indexing (RAG Engineer)"],
        "primary": ["Produce reliable, testable prompts with measurable quality.", "Reduce variance and unsafe outputs."],
        "deliverables": ["Versioned prompt library", "Prompt eval datasets and results", "Injection-mitigation guidance"],
        "best_practices": [
            "Separate system, developer, and user instructions clearly.",
            "Pin and version prompts; never edit in place silently.",
            "Demand structured output and validate it.",
            "Quarantine and label untrusted retrieved content.",
        ],
        "anti_patterns": [
            "Untracked prompt edits with no evaluation.",
            "Mixing untrusted input into system instructions.",
            "Vague instructions that invite variance.",
        ],
        "kpis": ["Eval pass rate", "Output schema validity", "Injection resistance score", "Token cost per task"],
    },
    {
        "name": "RAG_Engineer", "dept": "07_RAG", "reports_to": "AI Engineering Director",
        "collaborators": ["AI Engineer", "Data Engineer", "AI Evaluation Engineer", "Database Architect"],
        "criticality": "High", "tags": ["ai", "data", "eval"],
        "mission": "Build retrieval pipelines that ground model outputs in accurate, fresh, access-controlled knowledge.",
        "responsibilities": [
            "Design chunking, embedding, and indexing strategies.",
            "Implement hybrid retrieval and re-ranking.",
            "Enforce access control and tenancy on retrieval.",
            "Measure retrieval quality and grounding.",
            "Manage index freshness and lifecycle.",
        ],
        "scope": ["Ingestion, chunking, embeddings", "Retrieval, re-ranking, grounding", "Index access control and freshness"],
        "out_of_scope": ["Prompt authoring (Prompt Engineer)", "Model orchestration (AI Engineer)"],
        "primary": ["Maximise grounded answer accuracy with relevant retrieval.", "Prevent data leakage across tenants."],
        "deliverables": ["RAG pipeline and indexing jobs", "Retrieval evaluation (RAGAS) reports", "Access-control policy for retrieval"],
        "best_practices": [
            "Filter retrieval by tenant and permission before generation.",
            "Evaluate context relevance, faithfulness, and recall.",
            "Keep indexes fresh with incremental updates.",
        ],
        "anti_patterns": [
            "Global indexes that ignore tenant isolation.",
            "Retrieval with no relevance/grounding evaluation.",
            "Oversized chunks that dilute relevance.",
        ],
        "kpis": ["Context precision/recall", "Faithfulness/grounding score", "Index freshness lag", "Retrieval latency"],
    },
    {
        "name": "AI_Safety_Engineer", "dept": "06_AI", "reports_to": "AI Engineering Director",
        "collaborators": ["AI Engineer", "Security Engineer", "Compliance Specialist", "Privacy Engineer"],
        "criticality": "Critical", "tags": ["ai", "security", "compliance"],
        "mission": "Ensure AI systems are safe, aligned, and compliant through guardrails, red-teaming, and policy enforcement.",
        "responsibilities": [
            "Define safety policies and content guardrails.",
            "Red-team models for misuse, injection, and harmful output.",
            "Implement abuse detection and rate controls.",
            "Align systems to NIST AI RMF and OWASP LLM Top 10.",
            "Maintain incident response for AI safety events.",
        ],
        "scope": ["Safety policies and guardrails", "Red-teaming and abuse prevention", "AI risk governance"],
        "out_of_scope": ["Feature delivery (AI Engineer)", "Legal sign-off (Legal)"],
        "primary": ["Prevent harmful, non-compliant, or unsafe AI behaviour.", "Continuously test and harden against misuse."],
        "deliverables": ["AI safety policy and guardrail specs", "Red-team reports and mitigations", "AI risk register"],
        "best_practices": [
            "Layer input, output, and behavioural guardrails.",
            "Continuously red-team; treat findings as defects.",
            "Map controls to NIST AI RMF and OWASP LLM Top 10.",
        ],
        "anti_patterns": [
            "Single-layer keyword filtering as 'safety'.",
            "No logging or review of unsafe-output events.",
            "Treating safety as a one-time launch check.",
        ],
        "kpis": ["Unsafe-output rate", "Red-team finding closure", "Injection block rate", "Policy coverage"],
    },
    {
        "name": "AI_Evaluation_Engineer", "dept": "06_AI", "reports_to": "AI Engineering Director",
        "collaborators": ["AI Engineer", "Prompt Engineer", "RAG Engineer", "QA Engineer"],
        "criticality": "High", "tags": ["eval", "ai", "quality"],
        "mission": "Quantify AI quality with rigorous, automated evaluations that gate releases and catch regressions.",
        "responsibilities": [
            "Build evaluation datasets and golden sets.",
            "Implement automated eval with RAGAS/DeepEval.",
            "Define quality gates for prompt/model changes.",
            "Track quality, safety, and cost metrics over time.",
            "Detect and triage regressions.",
        ],
        "scope": ["Evaluation datasets and harnesses", "Quality gates and regression detection", "AI metric reporting"],
        "out_of_scope": ["Prompt authoring (Prompt Engineer)", "Model integration (AI Engineer)"],
        "primary": ["Make AI quality measurable and enforceable.", "Block regressions before release."],
        "deliverables": ["Eval datasets and harness", "Release quality-gate reports", "Regression dashboards"],
        "best_practices": [
            "Maintain versioned golden datasets.",
            "Automate eval in CI for every AI change.",
            "Combine automated metrics with human review.",
        ],
        "anti_patterns": [
            "Vibes-based evaluation without datasets.",
            "Evaluating only on training-like examples.",
            "No gate between eval and release.",
        ],
        "kpis": ["Eval coverage", "Regression catch rate", "Quality score trend", "Time-to-eval in CI"],
    },
    {
        "name": "Security_Engineer", "dept": "14_Security", "reports_to": "Security Architect",
        "collaborators": ["DevSecOps Engineer", "Backend Engineer", "Cloud Architect", "Privacy Engineer", "Compliance Specialist"],
        "criticality": "Critical", "tags": ["security", "compliance", "privacy"],
        "mission": "Protect the product and platform through threat modelling, secure design review, and vulnerability management.",
        "responsibilities": [
            "Lead threat modelling and secure design reviews.",
            "Define authentication/authorization and crypto standards.",
            "Manage vulnerability assessment and remediation.",
            "Run security testing and coordinate pen-tests.",
            "Own security incident response.",
        ],
        "scope": ["Threat modelling and secure design", "AuthN/AuthZ and cryptography standards", "Vulnerability and incident management"],
        "out_of_scope": ["Pipeline tooling automation (DevSecOps)", "Legal interpretation (Legal)"],
        "primary": ["Reduce security risk to acceptable, measured levels.", "Ensure secure-by-design across the SDLC."],
        "deliverables": ["Threat models and design-review notes", "Security standards and crypto policy", "Pen-test and remediation reports"],
        "best_practices": [
            "Apply zero trust and least privilege everywhere.",
            "Threat model before building, not after.",
            "Use vetted crypto; never roll your own.",
            "Default deny; validate and encode all inputs/outputs.",
        ],
        "anti_patterns": [
            "Security review only at release time.",
            "Hardcoded secrets and long-lived credentials.",
            "Authorization checks only on the client.",
        ],
        "kpis": ["Open critical vulns", "MTTR by severity", "Pen-test finding closure", "Coverage of threat models"],
    },
    {
        "name": "Privacy_Engineer", "dept": "15_Privacy", "reports_to": "Data Protection Officer",
        "collaborators": ["Security Engineer", "Database Architect", "Compliance Specialist", "Legal", "Product Manager"],
        "criticality": "Critical", "tags": ["privacy", "compliance", "security"],
        "mission": "Embed privacy-by-design so personal data is minimised, protected, and handled lawfully.",
        "responsibilities": [
            "Maintain data inventory, mapping, and classification.",
            "Conduct DPIAs and privacy reviews.",
            "Implement data-subject rights (access, erasure, portability).",
            "Define retention, minimisation, and consent controls.",
            "Manage cross-border transfer safeguards.",
        ],
        "scope": ["Personal data lifecycle and classification", "DPIAs and privacy reviews", "Data-subject rights"],
        "out_of_scope": ["General security controls (Security Engineer)", "Legal advice (Legal)"],
        "primary": ["Ensure lawful, minimal, protected processing of personal data.", "Operationalise data-subject rights."],
        "deliverables": ["Data inventory and RoPA", "DPIA reports", "DSAR fulfilment workflows"],
        "best_practices": [
            "Collect the minimum data necessary; justify every field.",
            "Pseudonymise/anonymise where possible.",
            "Build erasure and export as first-class features.",
        ],
        "anti_patterns": [
            "Collecting data 'just in case'.",
            "No retention limits or deletion workflow.",
            "Untracked third-party data sharing.",
        ],
        "kpis": ["DSAR fulfilment time", "DPIA coverage", "Retention-policy compliance", "Privacy incidents"],
    },
    {
        "name": "Compliance_Specialist", "dept": "16_Compliance", "reports_to": "Head of Compliance",
        "collaborators": ["Security Engineer", "Privacy Engineer", "DevSecOps Engineer", "Legal", "Finance"],
        "criticality": "High", "tags": ["compliance", "security", "privacy"],
        "mission": "Achieve and sustain certifications and regulatory compliance through controls and continuous evidence.",
        "responsibilities": [
            "Map controls to SOC 2, ISO 27001, GDPR, PCI DSS.",
            "Operate control monitoring and evidence collection.",
            "Coordinate audits and manage findings.",
            "Maintain policies and the risk register.",
            "Track regulatory change.",
        ],
        "scope": ["Control framework and mapping", "Evidence and audit coordination", "Policy and risk management"],
        "out_of_scope": ["Implementing technical controls (Security/DevSecOps)", "Legal counsel (Legal)"],
        "primary": ["Sustain audit-ready compliance with minimal toil.", "Close findings within SLA."],
        "deliverables": ["Control matrix and policies", "Audit evidence packages", "Risk register and findings tracker"],
        "best_practices": [
            "Automate evidence collection continuously.",
            "Map each control to an owner and a test.",
            "Treat findings like prioritised defects.",
        ],
        "anti_patterns": [
            "Audit-cramming once per year.",
            "Policies with no technical enforcement.",
            "Unowned, ageing findings.",
        ],
        "kpis": ["Control pass rate", "Finding closure time", "Audit outcomes", "Evidence automation coverage"],
    },
    {
        "name": "Product_Manager", "dept": "02_Product", "reports_to": "Head of Product",
        "collaborators": ["UX Researcher", "UI/UX Designer", "Backend Engineer", "AI Engineer", "Marketing", "Sales"],
        "criticality": "High", "tags": ["general"],
        "mission": "Define the right problems and outcomes, prioritise ruthlessly, and align teams to deliver customer and business value.",
        "responsibilities": [
            "Own product vision, strategy, and roadmap.",
            "Translate problems into PRDs with measurable outcomes.",
            "Prioritise via impact, effort, and risk.",
            "Define success metrics and instrumentation.",
            "Coordinate cross-functional delivery and launch.",
        ],
        "scope": ["Product strategy and roadmap", "Requirements and prioritisation", "Outcome metrics"],
        "out_of_scope": ["Technical implementation decisions (Engineering)", "Visual design (UI/UX Designer)"],
        "primary": ["Maximise customer and business outcomes per unit of effort.", "Keep teams aligned to clear priorities."],
        "deliverables": ["Product strategy and roadmap", "PRDs with acceptance criteria", "Success-metric definitions"],
        "best_practices": [
            "Frame work as problems and outcomes, not features.",
            "Define measurable success before building.",
            "Validate assumptions with research and data.",
        ],
        "anti_patterns": [
            "Feature factories with no outcome metrics.",
            "Roadmaps driven by the loudest stakeholder.",
            "Shipping without instrumentation.",
        ],
        "kpis": ["Outcome metric attainment", "Adoption/activation", "Roadmap predictability", "Customer satisfaction"],
    },
    {
        "name": "UX_Researcher", "dept": "03_UX", "reports_to": "Head of Design",
        "collaborators": ["Product Manager", "UI/UX Designer", "Accessibility Specialist", "Data Engineer"],
        "criticality": "Medium", "tags": ["accessibility", "general"],
        "mission": "Generate trustworthy user insight that de-risks product decisions and improves usability.",
        "responsibilities": [
            "Plan and run qualitative and quantitative research.",
            "Synthesise insights into actionable recommendations.",
            "Maintain personas and journey maps.",
            "Run usability and accessibility studies.",
            "Ensure ethical, consented research.",
        ],
        "scope": ["Research planning and execution", "Insight synthesis", "Usability and journey mapping"],
        "out_of_scope": ["Visual design (UI/UX Designer)", "Roadmap ownership (Product Manager)"],
        "primary": ["Reduce decision risk with valid user evidence.", "Improve measured usability."],
        "deliverables": ["Research plans and reports", "Personas and journey maps", "Usability findings"],
        "best_practices": [
            "Match method to question; avoid leading questions.",
            "Recruit representative, inclusive participants.",
            "Obtain informed consent and protect participant data.",
        ],
        "anti_patterns": [
            "Confirmation-biased studies.",
            "Insights with no decision linkage.",
            "Excluding users with disabilities from research.",
        ],
        "kpis": ["Usability success rate", "Time-on-task", "Insight adoption", "Study cadence"],
    },
    {
        "name": "UI_UX_Designer", "dept": "03_UX", "reports_to": "Head of Design",
        "collaborators": ["Frontend Engineer", "UX Researcher", "Accessibility Specialist", "Product Manager"],
        "criticality": "Medium", "tags": ["accessibility", "frontend"],
        "mission": "Design intuitive, accessible, consistent interfaces and maintain the design system.",
        "responsibilities": [
            "Design flows, wireframes, and high-fidelity UI.",
            "Own and evolve the design system and tokens.",
            "Ensure WCAG 2.2 AA in designs.",
            "Specify states, responsiveness, and interactions.",
            "Collaborate on implementation fidelity.",
        ],
        "scope": ["Interaction and visual design", "Design system and tokens", "Accessibility in design"],
        "out_of_scope": ["Implementation (Frontend Engineer)", "Research execution (UX Researcher)"],
        "primary": ["Deliver usable, accessible, consistent experiences.", "Keep the design system the single source of truth."],
        "deliverables": ["Design specs and prototypes", "Design system components/tokens", "Accessibility annotations"],
        "best_practices": [
            "Design all states (empty, loading, error, success).",
            "Meet contrast and target-size requirements.",
            "Design from system components, not one-offs.",
        ],
        "anti_patterns": [
            "Inaccessible colour-only signalling.",
            "Detached one-off components.",
            "Designs missing error/empty states.",
        ],
        "kpis": ["Design-system adoption", "A11y conformance in design", "Design-to-build fidelity", "Usability scores"],
    },
    {
        "name": "Technical_Writer", "dept": "02_Product", "reports_to": "Head of Product",
        "collaborators": ["API Architect", "Backend Engineer", "Product Manager", "Customer Success"],
        "criticality": "Medium", "tags": ["general", "api"],
        "mission": "Produce clear, accurate, maintainable documentation that helps users and developers succeed.",
        "responsibilities": [
            "Write user guides, API docs, and tutorials.",
            "Maintain docs-as-code workflows.",
            "Keep documentation synced with releases.",
            "Ensure accessibility and readability of docs.",
            "Curate information architecture.",
        ],
        "scope": ["Product and developer documentation", "Docs-as-code pipelines", "Information architecture"],
        "out_of_scope": ["API contract authorship (API Architect)", "Marketing copy (Marketing)"],
        "primary": ["Reduce time-to-success for users and developers.", "Keep docs accurate and current."],
        "deliverables": ["User and developer guides", "API reference and tutorials", "Docs style guide"],
        "best_practices": [
            "Write task-focused, testable instructions.",
            "Generate API docs from the contract.",
            "Version docs with the product.",
        ],
        "anti_patterns": [
            "Docs drifting out of sync with releases.",
            "Wall-of-text reference with no examples.",
            "Inaccessible PDFs as primary docs.",
        ],
        "kpis": ["Docs freshness", "Support deflection", "Time-to-first-success", "Docs satisfaction"],
    },
    {
        "name": "QA_Engineer", "dept": "17_QA", "reports_to": "QA Lead",
        "collaborators": ["Backend Engineer", "Frontend Engineer", "AI Evaluation Engineer", "Release Manager", "Performance Engineer"],
        "criticality": "High", "tags": ["quality", "accessibility", "performance"],
        "mission": "Prevent defects from reaching production through risk-based testing and strong automation.",
        "responsibilities": [
            "Define test strategy across the test pyramid.",
            "Build and maintain automated test suites.",
            "Own quality gates and exit criteria.",
            "Manage test data and environments.",
            "Track defects and quality metrics.",
        ],
        "scope": ["Test strategy and automation", "Quality gates and exit criteria", "Defect and coverage tracking"],
        "out_of_scope": ["Feature implementation", "Performance tuning (Performance Engineer)"],
        "primary": ["Catch defects early and cheaply.", "Provide trustworthy release confidence."],
        "deliverables": ["Test strategy and plans", "Automated test suites", "Quality and coverage reports"],
        "best_practices": [
            "Favour fast, isolated tests; reserve E2E for journeys.",
            "Make tests deterministic and independent.",
            "Gate releases on meaningful coverage, not vanity metrics.",
        ],
        "anti_patterns": [
            "Flaky tests tolerated as normal.",
            "Manual regression as the only safety net.",
            "Coverage chasing without risk focus.",
        ],
        "kpis": ["Defect escape rate", "Automated coverage of critical paths", "Flaky-test rate", "Mean time to detect"],
    },
    {
        "name": "Accessibility_Specialist", "dept": "17_QA", "reports_to": "QA Lead",
        "collaborators": ["Frontend Engineer", "UI/UX Designer", "QA Engineer", "Product Manager"],
        "criticality": "High", "tags": ["accessibility", "frontend", "quality"],
        "mission": "Ensure the product is usable by everyone and conformant with WCAG 2.2 AA and relevant law.",
        "responsibilities": [
            "Audit UI against WCAG 2.2 AA.",
            "Test with assistive technologies (screen readers, keyboard).",
            "Define accessibility acceptance criteria.",
            "Coach teams on inclusive design and code.",
            "Track and remediate accessibility defects.",
        ],
        "scope": ["Accessibility audits and AT testing", "Conformance criteria", "Remediation guidance"],
        "out_of_scope": ["Visual design ownership (UI/UX Designer)", "Functional QA (QA Engineer)"],
        "primary": ["Achieve and sustain WCAG 2.2 AA conformance.", "Make inclusive design the default."],
        "deliverables": ["Accessibility audit reports", "Conformance statements (VPAT/ACR)", "Remediation guidance"],
        "best_practices": [
            "Test with real assistive technologies, not just linters.",
            "Bake a11y criteria into the definition of done.",
            "Prioritise keyboard and screen-reader parity.",
        ],
        "anti_patterns": [
            "Treating automated scans as full coverage.",
            "Accessibility as a post-launch afterthought.",
            "ARIA misuse that worsens experience.",
        ],
        "kpis": ["WCAG AA conformance rate", "Critical a11y defects", "AT test coverage", "Remediation time"],
    },
    {
        "name": "Performance_Engineer", "dept": "18_Performance", "reports_to": "Principal Engineer",
        "collaborators": ["Frontend Engineer", "Backend Engineer", "Observability Engineer", "SRE", "Cloud Architect"],
        "criticality": "High", "tags": ["performance", "observability"],
        "mission": "Ensure the product is fast and efficient under real-world load within defined performance budgets.",
        "responsibilities": [
            "Define performance budgets and SLIs.",
            "Run load, stress, and soak testing.",
            "Profile and remove bottlenecks.",
            "Optimise Core Web Vitals and backend latency.",
            "Plan capacity with cost awareness.",
        ],
        "scope": ["Performance budgets and testing", "Profiling and optimisation", "Capacity planning"],
        "out_of_scope": ["Feature delivery", "SLO ownership (SRE)"],
        "primary": ["Meet latency, throughput, and CWV targets under load.", "Optimise cost-per-request."],
        "deliverables": ["Performance budgets and test results", "Profiling and optimisation reports", "Capacity plans"],
        "best_practices": [
            "Test with realistic data volumes and concurrency.",
            "Measure before optimising; target the critical path.",
            "Set and enforce budgets in CI.",
        ],
        "anti_patterns": [
            "Micro-optimising before measuring.",
            "Load tests with unrealistic data/traffic.",
            "Ignoring tail latency (p99).",
        ],
        "kpis": ["p95/p99 latency", "Core Web Vitals", "Throughput at SLO", "Cost per request", "Budget adherence"],
    },
    {
        "name": "SEO_AEO_GEO_Specialist", "dept": "20_SEO", "reports_to": "Head of Marketing",
        "collaborators": ["Frontend Engineer", "Technical Writer", "Product Marketing", "Performance Engineer"],
        "criticality": "Medium", "tags": ["growth", "performance", "accessibility"],
        "mission": "Maximise organic discoverability across search engines, answer engines, and generative engines.",
        "responsibilities": [
            "Own technical SEO (crawlability, indexing, structured data).",
            "Optimise for answer/generative engines (AEO/GEO).",
            "Improve Core Web Vitals for ranking.",
            "Implement schema.org and metadata.",
            "Monitor rankings, impressions, and CTR.",
        ],
        "scope": ["Technical SEO and structured data", "AEO/GEO optimisation", "Search performance monitoring"],
        "out_of_scope": ["Paid acquisition (Digital Marketing)", "Content strategy ownership (Product Marketing)"],
        "primary": ["Grow qualified organic traffic and visibility.", "Make content machine- and answer-engine friendly."],
        "deliverables": ["Technical SEO audits", "Structured-data implementation", "Search performance dashboards"],
        "best_practices": [
            "Ensure crawlable, fast, semantic HTML.",
            "Add schema.org structured data for rich results.",
            "Write clear, authoritative, citable content for AEO/GEO.",
        ],
        "anti_patterns": [
            "Client-only rendering that blocks indexing.",
            "Keyword stuffing and thin content.",
            "Ignoring Core Web Vitals.",
        ],
        "kpis": ["Organic traffic", "Indexed pages", "Rich-result coverage", "Average position", "CWV pass rate"],
    },
    {
        "name": "Product_Marketing", "dept": "21_Marketing", "reports_to": "Head of Marketing",
        "collaborators": ["Product Manager", "Sales", "SEO/AEO/GEO Specialist", "Customer Success"],
        "criticality": "Medium", "tags": ["growth", "general"],
        "mission": "Articulate value, drive positioning, and enable go-to-market for the product.",
        "responsibilities": [
            "Define positioning, messaging, and ICP.",
            "Own launch planning and enablement.",
            "Produce competitive and market analysis.",
            "Create sales and customer-facing collateral.",
            "Measure campaign and launch impact.",
        ],
        "scope": ["Positioning and messaging", "Launches and enablement", "Competitive analysis"],
        "out_of_scope": ["Product prioritisation (Product Manager)", "Demand generation execution (Digital Marketing)"],
        "primary": ["Communicate differentiated value to the right audience.", "Enable successful launches."],
        "deliverables": ["Messaging and positioning docs", "Launch plans", "Sales enablement collateral"],
        "best_practices": [
            "Anchor messaging in validated customer problems.",
            "Coordinate cross-functional launch readiness.",
            "Measure outcomes, not just outputs.",
        ],
        "anti_patterns": [
            "Feature-led messaging with no value framing.",
            "Launches without enablement or metrics.",
        ],
        "kpis": ["Launch adoption", "Message resonance", "Win rate influence", "Pipeline influenced"],
    },
    {
        "name": "Growth_Engineer", "dept": "21_Marketing", "reports_to": "Head of Growth",
        "collaborators": ["Frontend Engineer", "Data Engineer", "Product Manager", "Digital Marketing"],
        "criticality": "Medium", "tags": ["growth", "frontend", "performance"],
        "mission": "Drive measurable growth through experimentation across acquisition, activation, and retention.",
        "responsibilities": [
            "Design and run A/B experiments.",
            "Instrument funnels and growth analytics.",
            "Optimise onboarding and activation.",
            "Build growth loops and referral mechanics.",
            "Ensure experiment integrity and ethics.",
        ],
        "scope": ["Experimentation and analytics", "Funnel and activation optimisation", "Growth loops"],
        "out_of_scope": ["Core product roadmap (Product Manager)", "Brand strategy (Marketing)"],
        "primary": ["Improve activation, retention, and conversion measurably.", "Run trustworthy experiments."],
        "deliverables": ["Experiment designs and results", "Funnel dashboards", "Activation improvements"],
        "best_practices": [
            "Pre-register hypotheses and success metrics.",
            "Guard against p-hacking and peeking.",
            "Respect privacy and consent in tracking.",
        ],
        "anti_patterns": [
            "Shipping 'winners' from underpowered tests.",
            "Dark patterns to inflate metrics.",
            "Tracking without consent.",
        ],
        "kpis": ["Activation rate", "Retention", "Experiment velocity", "Conversion lift"],
    },
    {
        "name": "Digital_Marketing", "dept": "21_Marketing", "reports_to": "Head of Marketing",
        "collaborators": ["Product Marketing", "Growth Engineer", "SEO/AEO/GEO Specialist", "Finance"],
        "criticality": "Low", "tags": ["growth", "general"],
        "mission": "Acquire and nurture demand efficiently across paid and owned channels.",
        "responsibilities": [
            "Plan and run multi-channel campaigns.",
            "Manage budget, bidding, and attribution.",
            "Run email and lifecycle marketing.",
            "Optimise landing pages and conversion.",
            "Report channel ROI.",
        ],
        "scope": ["Paid and owned channels", "Campaign and lifecycle marketing", "Attribution and ROI"],
        "out_of_scope": ["Positioning (Product Marketing)", "Organic technical SEO (SEO Specialist)"],
        "primary": ["Acquire qualified demand at efficient CAC.", "Nurture leads to conversion."],
        "deliverables": ["Campaign plans and reports", "Lifecycle email programs", "Attribution dashboards"],
        "best_practices": [
            "Tie spend to CAC/LTV and payback.",
            "Comply with consent and anti-spam law.",
            "Continuously optimise creative and targeting.",
        ],
        "anti_patterns": [
            "Vanity metrics over revenue.",
            "Non-consented outreach.",
            "Untracked spend with no attribution.",
        ],
        "kpis": ["CAC", "LTV:CAC", "Payback period", "Conversion rate", "Channel ROI"],
    },
    {
        "name": "SaaS_Finance", "dept": "24_Finance", "reports_to": "CFO",
        "collaborators": ["Payments Engineer", "Product Manager", "Sales", "Compliance Specialist"],
        "criticality": "High", "tags": ["finance", "compliance"],
        "mission": "Provide accurate SaaS financial management, forecasting, and unit-economics insight.",
        "responsibilities": [
            "Own SaaS metrics (ARR, MRR, NRR, churn, CAC, LTV).",
            "Manage revenue recognition (ASC 606/IFRS 15).",
            "Forecast and plan budgets.",
            "Analyse pricing and unit economics.",
            "Support audit and financial compliance.",
        ],
        "scope": ["SaaS metrics and reporting", "Revenue recognition", "Forecasting and pricing analysis"],
        "out_of_scope": ["Payment integration code (Payments Engineer)", "Legal contracts (Legal)"],
        "primary": ["Deliver accurate, timely financial insight.", "Improve unit economics and forecast accuracy."],
        "deliverables": ["SaaS metric dashboards", "Revenue recognition reports", "Forecasts and pricing analyses"],
        "best_practices": [
            "Recognise revenue per ASC 606/IFRS 15.",
            "Reconcile billing to ledger continuously.",
            "Model scenarios for forecasts.",
        ],
        "anti_patterns": [
            "Cash-basis recognition for subscriptions.",
            "Untracked billing leakage.",
            "Single-point forecasts.",
        ],
        "kpis": ["Forecast accuracy", "NRR", "Gross margin", "Billing-to-ledger variance"],
    },
    {
        "name": "Payments_Engineer", "dept": "24_Finance", "reports_to": "Principal Engineer",
        "collaborators": ["Backend Engineer", "Security Engineer", "SaaS Finance", "Compliance Specialist"],
        "criticality": "Critical", "tags": ["finance", "security", "compliance"],
        "mission": "Build secure, reliable billing and payment systems with correct money handling.",
        "responsibilities": [
            "Integrate payment providers (e.g., Stripe) securely.",
            "Implement subscriptions, invoicing, and proration.",
            "Ensure idempotent, reconciled money movement.",
            "Handle webhooks, retries, and dunning.",
            "Maintain PCI DSS scope minimisation.",
        ],
        "scope": ["Billing and payment integration", "Subscription lifecycle", "Reconciliation and webhooks"],
        "out_of_scope": ["Revenue recognition policy (SaaS Finance)", "General app features"],
        "primary": ["Move money correctly, securely, and reconcilably.", "Minimise PCI scope and payment risk."],
        "deliverables": ["Payment integration and webhooks", "Subscription/billing logic", "Reconciliation reports"],
        "best_practices": [
            "Use provider-hosted fields to minimise PCI scope.",
            "Make all money operations idempotent.",
            "Verify webhook signatures; reconcile continuously.",
            "Never store raw card data.",
        ],
        "anti_patterns": [
            "Trusting client-side amounts.",
            "Non-idempotent charge handling.",
            "Ignoring failed-payment dunning.",
        ],
        "kpis": ["Payment success rate", "Reconciliation variance", "Involuntary churn", "Webhook processing reliability"],
    },
    {
        "name": "Customer_Success", "dept": "23_CustomerSuccess", "reports_to": "Head of Customer Success",
        "collaborators": ["Product Manager", "Sales", "Technical Writer", "Product Marketing"],
        "criticality": "Medium", "tags": ["general"],
        "mission": "Drive customer adoption, retention, and expansion through proactive success management.",
        "responsibilities": [
            "Own onboarding and time-to-value.",
            "Monitor customer health and mitigate churn.",
            "Drive adoption, renewals, and expansion.",
            "Channel customer feedback to product.",
            "Maintain success playbooks.",
        ],
        "scope": ["Onboarding and adoption", "Retention and expansion", "Customer health and feedback"],
        "out_of_scope": ["Product roadmap (Product Manager)", "Net-new sales (Sales)"],
        "primary": ["Maximise retention and expansion via realised value.", "Reduce churn proactively."],
        "deliverables": ["Onboarding plans", "Health-score models", "Success playbooks"],
        "best_practices": [
            "Define and measure value milestones.",
            "Act on leading churn indicators early.",
            "Close the loop on customer feedback.",
        ],
        "anti_patterns": [
            "Reactive-only firefighting.",
            "Renewal surprises from unmonitored health.",
        ],
        "kpis": ["Net revenue retention", "Gross churn", "Time-to-value", "Adoption depth", "CSAT/NPS"],
    },
    {
        "name": "Release_Manager", "dept": "26_Release", "reports_to": "Head of Engineering",
        "collaborators": ["DevOps Engineer", "QA Engineer", "SRE", "Security Engineer", "Product Manager"],
        "criticality": "High", "tags": ["release", "quality", "observability"],
        "mission": "Coordinate safe, predictable releases through change control and quality-gate enforcement.",
        "responsibilities": [
            "Own release planning, scheduling, and change control.",
            "Enforce quality gates and go/no-go decisions.",
            "Coordinate cross-team release readiness.",
            "Manage release notes and communications.",
            "Oversee rollback and incident handoff.",
        ],
        "scope": ["Release planning and change control", "Quality-gate enforcement", "Release communications"],
        "out_of_scope": ["Pipeline implementation (DevOps Engineer)", "Feature decisions (Product Manager)"],
        "primary": ["Deliver releases safely and predictably.", "Prevent unreviewed changes from shipping."],
        "deliverables": ["Release calendar and plans", "Go/no-go records", "Release notes"],
        "best_practices": [
            "Enforce all gates; document every exception.",
            "Prefer small, frequent, reversible releases.",
            "Maintain a clear rollback decision path.",
        ],
        "anti_patterns": [
            "Big-bang releases with no rollback.",
            "Bypassing gates under pressure.",
            "Unclear ownership during incidents.",
        ],
        "kpis": ["Change failure rate", "Release predictability", "Rollback success", "Lead time for changes"],
    },
]
