"""Data tables for ASFE Rules, Checklists, Playbooks, Templates and Knowledge."""

# ---------------------------------------------------------------------------
# RULES (24) - name, category, applies_to, priority, owner, tags, statement,
#              musts[], shoulds[], mays[], anti[]
# ---------------------------------------------------------------------------
RULES = [
    {"name": "API_Standards", "category": "Engineering", "applies_to": "All APIs", "priority": "Critical",
     "owner": "API Architect", "tags": ["api", "backend", "security"],
     "statement": "All APIs MUST be contract-first, versioned, consistent, and secure by default.",
     "musts": ["Publish an OpenAPI 3.1 contract as the source of truth before implementation.",
               "Use explicit versioning and a documented deprecation policy.",
               "Return errors using RFC 9457 problem-details.",
               "Authenticate and authorize every endpoint; default deny.",
               "Validate and constrain all inputs; enforce pagination limits."],
     "shoulds": ["Provide idempotency keys for mutating endpoints.",
                 "Offer consistent filtering, sorting, and pagination conventions.",
                 "Publish consumer-driven contract tests."],
     "mays": ["Provide GraphQL or gRPC alongside REST where justified.",
              "Expose an AsyncAPI contract for event streams."],
     "anti": ["Leaking internal models as responses.",
              "Silent breaking changes to field shapes or semantics.",
              "Inconsistent error formats across endpoints."]},
    {"name": "Coding_Standards", "category": "Engineering", "applies_to": "All source code", "priority": "High",
     "owner": "Principal Engineer", "tags": ["general", "security"],
     "statement": "Code MUST be readable, tested, secure, and consistently formatted.",
     "musts": ["Pass automated linting and formatting in CI.",
               "Include tests for new and changed behaviour.",
               "Avoid hardcoded secrets and credentials.",
               "Handle errors explicitly; never silently swallow them."],
     "shoulds": ["Keep functions small and single-purpose.",
                 "Prefer composition and clear naming over cleverness.",
                 "Document non-obvious intent, not the obvious."],
     "mays": ["Adopt language-specific idioms documented per repo."],
     "anti": ["Dead code and commented-out blocks.",
              "Copy-paste duplication instead of abstraction.",
              "Magic numbers without named constants."]},
    {"name": "Security_Standards", "category": "Security", "applies_to": "All systems", "priority": "Critical",
     "owner": "Security Architect", "tags": ["security", "compliance", "privacy"],
     "statement": "Systems MUST be secure by design, applying zero trust and least privilege.",
     "musts": ["Threat model features before implementation.",
               "Encrypt data in transit (TLS 1.2+) and at rest.",
               "Enforce least-privilege access and short-lived credentials.",
               "Validate, sanitise, and encode all untrusted input/output.",
               "Pass SAST/DAST/SCA gates with no unresolved criticals."],
     "shoulds": ["Adopt MFA and phishing-resistant auth.",
                 "Rotate secrets automatically.",
                 "Conduct periodic penetration testing."],
     "mays": ["Use hardware-backed key storage (HSM/KMS)."],
     "anti": ["Rolling custom cryptography.",
              "Long-lived static credentials.",
              "Client-only authorization checks."]},
    {"name": "Authentication_And_Authorization", "category": "Security", "applies_to": "All access control", "priority": "Critical",
     "owner": "Security Engineer", "tags": ["security", "api"],
     "statement": "All access MUST be authenticated and authorized server-side using standards-based protocols.",
     "musts": ["Use OAuth 2.1 / OIDC for authentication.",
               "Enforce authorization on the server for every request.",
               "Apply role/attribute-based access control with least privilege.",
               "Expire and rotate tokens; support revocation."],
     "shoulds": ["Use short-lived access tokens with refresh rotation.",
                 "Log authn/authz decisions for audit."],
     "mays": ["Support step-up authentication for sensitive actions."],
     "anti": ["Trusting client-supplied roles or IDs.",
              "Storing passwords without modern hashing.",
              "Reusing long-lived tokens indefinitely."]},
    {"name": "Data_Protection_And_Privacy", "category": "Privacy", "applies_to": "All personal data", "priority": "Critical",
     "owner": "Privacy Engineer", "tags": ["privacy", "security", "compliance"],
     "statement": "Personal data MUST be minimised, protected, and processed lawfully.",
     "musts": ["Classify and inventory all personal data.",
               "Collect the minimum data necessary with a lawful basis.",
               "Support data-subject rights (access, erasure, portability).",
               "Apply retention limits and secure deletion."],
     "shoulds": ["Pseudonymise or anonymise where feasible.",
                 "Run DPIAs for high-risk processing."],
     "mays": ["Offer customer-managed encryption keys."],
     "anti": ["Collecting data 'just in case'.",
              "Indefinite retention with no policy.",
              "Untracked third-party data sharing."]},
    {"name": "Logging_And_Observability", "category": "Operations", "applies_to": "All services", "priority": "High",
     "owner": "Observability Engineer", "tags": ["observability", "security"],
     "statement": "Services MUST emit structured, correlated, privacy-safe telemetry.",
     "musts": ["Emit structured logs with correlation/trace IDs.",
               "Expose metrics aligned to SLIs.",
               "Propagate distributed traces (OpenTelemetry).",
               "Never log secrets or unmasked personal data."],
     "shoulds": ["Define retention and sampling to manage cost.",
                 "Alert on symptoms tied to SLOs."],
     "mays": ["Adopt exemplars linking metrics to traces."],
     "anti": ["Unstructured log spam.",
              "Logging credentials or PII.",
              "Alert fatigue from non-actionable alerts."]},
    {"name": "Error_Handling", "category": "Engineering", "applies_to": "All code", "priority": "High",
     "owner": "Principal Engineer", "tags": ["backend", "api"],
     "statement": "Errors MUST be handled explicitly, safely, and observably.",
     "musts": ["Fail safely without leaking internal details.",
               "Return consistent, typed error responses.",
               "Log errors with context and correlation IDs.",
               "Distinguish retryable from terminal errors."],
     "shoulds": ["Use circuit breakers and backoff for dependencies.",
                 "Surface actionable user-facing messages."],
     "mays": ["Provide error catalogues with remediation hints."],
     "anti": ["Swallowing exceptions silently.",
              "Leaking stack traces to clients.",
              "Generic 500s with no diagnostics."]},
    {"name": "Testing_Standards", "category": "Quality", "applies_to": "All code", "priority": "High",
     "owner": "QA Lead", "tags": ["quality"],
     "statement": "Changes MUST be protected by automated, deterministic tests across the test pyramid.",
     "musts": ["Cover new/changed behaviour with tests.",
               "Keep tests deterministic and isolated.",
               "Run tests in CI as a merge gate.",
               "Maintain meaningful coverage of critical paths."],
     "shoulds": ["Favour fast unit tests; reserve E2E for journeys.",
                 "Quarantine and fix flaky tests promptly."],
     "mays": ["Adopt mutation testing for critical modules."],
     "anti": ["Tolerating flaky tests.",
              "Coverage chasing without risk focus.",
              "Manual-only regression."]},
    {"name": "Git_And_Version_Control", "category": "Engineering", "applies_to": "All repositories", "priority": "Medium",
     "owner": "Engineering Manager", "tags": ["release", "general"],
     "statement": "Source control MUST use protected branches, reviews, and conventional history.",
     "musts": ["Require pull-request review before merge to main.",
               "Protect main with passing CI and no force-push.",
               "Use Conventional Commits.",
               "Never commit secrets; scan history."],
     "shoulds": ["Keep PRs small and focused.",
                 "Sign commits and tags."],
     "mays": ["Adopt trunk-based development."],
     "anti": ["Direct pushes to main.",
              "Giant, unreviewable PRs.",
              "Secrets committed to history."]},
    {"name": "CI_CD_Standards", "category": "Operations", "applies_to": "All pipelines", "priority": "High",
     "owner": "DevOps Engineer", "tags": ["release", "security", "cloud"],
     "statement": "Delivery MUST be automated, gated, and reproducible.",
     "musts": ["Build once and promote the same artifact.",
               "Gate releases on tests, scans, and policy.",
               "Automate rollback and post-deploy verification.",
               "Store no secrets in pipeline config."],
     "shoulds": ["Use progressive delivery (canary/blue-green).",
                 "Generate SBOMs and sign artifacts."],
     "mays": ["Adopt GitOps for deployments."],
     "anti": ["Manual deployment steps.",
              "Skipping gates under pressure.",
              "Environment-specific rebuilds."]},
    {"name": "Infrastructure_As_Code", "category": "Cloud", "applies_to": "All infrastructure", "priority": "High",
     "owner": "Cloud Architect", "tags": ["cloud", "security"],
     "statement": "Infrastructure MUST be declarative, reviewed, and reproducible.",
     "musts": ["Define all infrastructure as version-controlled code.",
               "Review IaC changes like application code.",
               "Apply policy-as-code guardrails.",
               "Prohibit manual click-ops in production."],
     "shoulds": ["Use immutable, reproducible builds.",
                 "Detect and remediate drift automatically."],
     "mays": ["Adopt reusable module registries."],
     "anti": ["Click-ops changes.",
              "Unreviewed infrastructure edits.",
              "Snowflake environments."]},
    {"name": "Secrets_Management", "category": "Security", "applies_to": "All secrets", "priority": "Critical",
     "owner": "Security Engineer", "tags": ["security", "cloud"],
     "statement": "Secrets MUST be centrally managed, encrypted, rotated, and never committed.",
     "musts": ["Store secrets in a dedicated secrets manager.",
               "Encrypt secrets at rest and in transit.",
               "Rotate secrets and credentials regularly.",
               "Scan code and history for leaked secrets."],
     "shoulds": ["Prefer short-lived, dynamically issued credentials.",
                 "Scope secrets to least privilege."],
     "mays": ["Use workload identity to avoid static secrets."],
     "anti": ["Secrets in code, env files, or images.",
              "Shared, long-lived credentials.",
              "No rotation policy."]},
    {"name": "Database_Standards", "category": "Engineering", "applies_to": "All databases", "priority": "High",
     "owner": "Database Architect", "tags": ["data", "backend", "security"],
     "statement": "Databases MUST ensure integrity, recoverability, and safe evolution.",
     "musts": ["Use reversible, expand-then-contract migrations.",
               "Encrypt data at rest; restrict access by role.",
               "Maintain tested backups with defined RPO/RTO.",
               "Use parameterised queries only."],
     "shoulds": ["Index for actual query patterns.",
                 "Partition and archive large datasets."],
     "mays": ["Adopt read replicas for scaling."],
     "anti": ["Destructive migrations with no rollback.",
              "Untested backups.",
              "Storing unclassified PII."]},
    {"name": "Accessibility_Standards", "category": "Quality", "applies_to": "All user interfaces", "priority": "High",
     "owner": "Accessibility Specialist", "tags": ["accessibility", "frontend"],
     "statement": "User interfaces MUST conform to WCAG 2.2 AA.",
     "musts": ["Provide semantic, keyboard-operable interfaces.",
               "Meet contrast and target-size requirements.",
               "Provide text alternatives for non-text content.",
               "Test with assistive technologies."],
     "shoulds": ["Include a11y criteria in the definition of done.",
                 "Publish a conformance statement (VPAT/ACR)."],
     "mays": ["Target select WCAG AAA criteria."],
     "anti": ["Colour-only signalling.",
              "Keyboard traps.",
              "ARIA misuse that harms experience."]},
    {"name": "Performance_Budgets", "category": "Performance", "applies_to": "All user-facing features", "priority": "High",
     "owner": "Performance Engineer", "tags": ["performance", "frontend"],
     "statement": "Features MUST meet defined performance budgets and Core Web Vitals.",
     "musts": ["Define and enforce performance budgets in CI.",
               "Meet Core Web Vitals (LCP, INP, CLS) targets.",
               "Test under realistic load before release.",
               "Track p95/p99 latency against SLOs."],
     "shoulds": ["Optimise critical rendering path.",
                 "Cache and compress responses appropriately."],
     "mays": ["Adopt edge rendering/CDN for latency."],
     "anti": ["Optimising before measuring.",
              "Ignoring tail latency.",
              "Unbounded payloads."]},
    {"name": "AI_LLM_Usage", "category": "AI", "applies_to": "All AI/LLM features", "priority": "Critical",
     "owner": "AI Engineering Director", "tags": ["ai", "security", "eval"],
     "statement": "AI/LLM features MUST be safe, evaluated, observable, and cost-controlled.",
     "musts": ["Constrain and validate model outputs before use.",
               "Apply input/output guardrails against injection and abuse.",
               "Gate prompt/model changes on automated evaluation.",
               "Never send secrets/PII to models without controls."],
     "shoulds": ["Add fallbacks, timeouts, and routing for model calls.",
                 "Instrument quality, latency, and cost telemetry."],
     "mays": ["Use a model gateway for routing and governance."],
     "anti": ["Trusting raw model output as executable.",
              "No evaluation gate before changes.",
              "Unbounded injection of untrusted content."]},
    {"name": "Prompt_Engineering_Standards", "category": "AI", "applies_to": "All prompts", "priority": "High",
     "owner": "Prompt Engineer", "tags": ["ai", "eval"],
     "statement": "Prompts MUST be versioned, evaluated, and resistant to injection.",
     "musts": ["Version prompts; never edit in place silently.",
               "Separate system/developer/user instructions.",
               "Evaluate prompt changes before release.",
               "Quarantine and label untrusted content."],
     "shoulds": ["Demand structured output and validate it.",
                 "Maintain few-shot exemplars."],
     "mays": ["Use templating with strict variable boundaries."],
     "anti": ["Untracked prompt edits.",
              "Mixing untrusted input into system prompts.",
              "Vague, high-variance instructions."]},
    {"name": "RAG_Standards", "category": "AI", "applies_to": "All retrieval pipelines", "priority": "High",
     "owner": "RAG Engineer", "tags": ["ai", "data", "eval"],
     "statement": "Retrieval MUST be access-controlled, grounded, fresh, and evaluated.",
     "musts": ["Enforce tenant and permission filters on retrieval.",
               "Evaluate context relevance and grounding (RAGAS).",
               "Keep indexes fresh with defined update cadence.",
               "Cite sources for grounded answers."],
     "shoulds": ["Use hybrid retrieval and re-ranking.",
                 "Right-size chunks for relevance."],
     "mays": ["Adopt semantic caching."],
     "anti": ["Global indexes ignoring tenancy.",
              "Retrieval with no grounding evaluation.",
              "Stale indexes."]},
    {"name": "Dependency_Management", "category": "Security", "applies_to": "All dependencies", "priority": "High",
     "owner": "DevSecOps Engineer", "tags": ["security", "release"],
     "statement": "Dependencies MUST be tracked, scanned, pinned, and kept current.",
     "musts": ["Pin and lock dependency versions.",
               "Scan dependencies for vulnerabilities (SCA).",
               "Maintain an SBOM.",
               "Remediate critical vulnerabilities within SLA."],
     "shoulds": ["Automate dependency updates with tests.",
                 "Prefer well-maintained, vetted libraries."],
     "mays": ["Use private registries with provenance."],
     "anti": ["Unpinned floating versions.",
              "Ignoring transitive risk.",
              "Stale, unpatched dependencies."]},
    {"name": "Documentation_Standards", "category": "Documentation", "applies_to": "All documentation", "priority": "Medium",
     "owner": "Technical Writer", "tags": ["general", "accessibility"],
     "statement": "Documentation MUST be accurate, versioned, accessible, and docs-as-code.",
     "musts": ["Version docs with the product.",
               "Generate API docs from contracts.",
               "Keep docs accurate and current at release.",
               "Meet accessibility and readability standards."],
     "shoulds": ["Provide task-focused, testable instructions.",
                 "Include examples and quickstarts."],
     "mays": ["Localise documentation."],
     "anti": ["Docs drifting from releases.",
              "Reference-only docs with no examples.",
              "Inaccessible formats."]},
    {"name": "Release_Management", "category": "Operations", "applies_to": "All releases", "priority": "High",
     "owner": "Release Manager", "tags": ["release", "quality"],
     "statement": "Releases MUST pass quality gates and be reversible.",
     "musts": ["Pass all required quality gates before release.",
               "Use semantic versioning.",
               "Provide a tested rollback path.",
               "Record go/no-go decisions."],
     "shoulds": ["Prefer small, frequent releases.",
                 "Communicate release notes clearly."],
     "mays": ["Use feature flags for progressive rollout."],
     "anti": ["Big-bang releases with no rollback.",
              "Bypassing gates.",
              "Undocumented changes."]},
    {"name": "Incident_Management", "category": "Operations", "applies_to": "All production incidents", "priority": "Critical",
     "owner": "Site Reliability Engineer", "tags": ["observability", "release", "security"],
     "statement": "Incidents MUST be managed with clear command, communication, and learning.",
     "musts": ["Declare incidents with defined severity and roles.",
               "Maintain communication during incidents.",
               "Conduct blameless postmortems with actions.",
               "Track and close remediation actions."],
     "shoulds": ["Maintain runbooks for common incidents.",
                 "Practise incident drills."],
     "mays": ["Automate incident tooling and paging."],
     "anti": ["No clear incident commander.",
              "Postmortems without owned actions.",
              "Blame culture."]},
    {"name": "Compliance_Standards", "category": "Compliance", "applies_to": "All regulated processing", "priority": "High",
     "owner": "Compliance Specialist", "tags": ["compliance", "security", "privacy"],
     "statement": "Operations MUST map to recognised control frameworks with continuous evidence.",
     "musts": ["Map controls to SOC 2 / ISO 27001 / GDPR / PCI as applicable.",
               "Assign an owner and test to each control.",
               "Collect audit evidence continuously.",
               "Track and close findings within SLA."],
     "shoulds": ["Automate evidence collection.",
                 "Maintain a current risk register."],
     "mays": ["Pursue additional certifications as needed."],
     "anti": ["Annual audit-cramming.",
              "Policies without enforcement.",
              "Unowned, ageing findings."]},
    {"name": "Frontend_Standards", "category": "Engineering", "applies_to": "All client applications", "priority": "High",
     "owner": "Frontend Lead", "tags": ["frontend", "accessibility", "performance"],
     "statement": "Frontends MUST be accessible, performant, secure, and component-driven.",
     "musts": ["Use the design system and semantic HTML.",
               "Meet WCAG 2.2 AA and Core Web Vitals budgets.",
               "Sanitise/escape untrusted content (prevent XSS).",
               "Validate API responses defensively."],
     "shoulds": ["Code-split and lazy-load non-critical paths.",
                 "Handle all UI states (loading/empty/error)."],
     "mays": ["Adopt SSR/edge rendering for performance/SEO."],
     "anti": ["Div-soup over semantic elements.",
              "Blocking the main thread.",
              "Rendering untrusted HTML unsanitised."]},
    {"name": "Data_Engineering_Standards", "category": "Engineering", "applies_to": "All data pipelines and datasets", "priority": "High",
     "owner": "Data Engineer", "tags": ["data", "backend", "privacy"],
     "statement": "Data pipelines MUST be reliable, tested, observable, and reproducible.",
     "musts": ["Make pipelines idempotent and safe to replay.",
               "Validate data quality with automated tests at boundaries.",
               "Instrument pipelines with logging, metrics, and lineage.",
               "Version pipeline code and evolve schemas backward-compatibly."],
     "shoulds": ["Treat datasets as products with owners and SLAs.",
                 "Document datasets in a data dictionary."],
     "mays": ["Adopt a lakehouse / medallion architecture."],
     "anti": ["Undocumented, untested pipelines.",
              "Silent schema drift breaking consumers.",
              "Manual, non-reproducible data fixes."]},
    {"name": "Data_Governance_Standards", "category": "Data", "applies_to": "All data assets", "priority": "High",
     "owner": "Data Engineer", "tags": ["data", "privacy", "compliance"],
     "statement": "Data MUST be classified, governed, and retained according to policy and law.",
     "musts": ["Classify data by sensitivity and ownership.",
               "Maintain data lineage and a searchable catalogue.",
               "Apply retention and deletion policies.",
               "Restrict access by least privilege and purpose."],
     "shoulds": ["Mask or tokenise sensitive fields outside production.",
                 "Audit data access regularly."],
     "mays": ["Adopt automated data-governance tooling."],
     "anti": ["Untracked, unclassified data sprawl.",
              "Copying PII into analytics or non-prod without controls.",
              "Indefinite retention with no policy."]},
    {"name": "Architecture_Governance_Standards", "category": "Architecture", "applies_to": "All significant technical decisions", "priority": "High",
     "owner": "Enterprise Architect", "tags": ["general", "cloud", "security"],
     "statement": "Significant architectural decisions MUST be reviewed and recorded.",
     "musts": ["Record significant decisions as ADRs with context and consequences.",
               "Pass architecture review before significant builds.",
               "Address security, scalability, resilience, and cost in designs.",
               "Align designs to the reference architecture and standards."],
     "shoulds": ["Define fitness functions for key quality attributes.",
                 "Track and manage technical debt explicitly."],
     "mays": ["Maintain a technology radar."],
     "anti": ["Undocumented, tribal decisions.",
              "Big up-front design with no iteration.",
              "Bypassing architecture review for significant changes."]},
    {"name": "Document_Lifecycle_Governance", "category": "Governance", "applies_to": "All framework documents", "priority": "Medium",
     "owner": "Enterprise Architect", "tags": ["general"],
     "statement": "Framework documents MUST follow a defined lifecycle: versioned, reviewed, and deliberately deprecated.",
     "musts": ["Use semantic versioning for documents.",
               "Assign each document an owner and review frequency.",
               "Review documents on the defined cadence.",
               "Mark superseded documents as deprecated with a successor."],
     "shoulds": ["Keep a version history per document.",
                 "Validate documents against the specification before publishing."],
     "mays": ["Automate document validation in CI."],
     "anti": ["Stale documents past their review date.",
              "Orphaned documents with no owner.",
              "Silent breaking changes to standards."]},
    {"name": "Contracting_Standards", "category": "Legal", "applies_to": "All customer and vendor contracts", "priority": "High",
     "owner": "Legal Counsel", "tags": ["compliance", "privacy", "general"],
     "statement": "Contracts MUST use approved templates and protect the business and its customers.",
     "musts": ["Use approved contract templates and fallback positions.",
               "Include a Data Processing Agreement where personal data is processed.",
               "Define clear SLAs, liability, and termination terms.",
               "Obtain legal review before signing non-standard terms."],
     "shoulds": ["Track obligations and renewal dates.",
                 "Align contracts with security and privacy commitments."],
     "mays": ["Use contract lifecycle management tooling."],
     "anti": ["Bespoke contracts with no playbook.",
              "Committing to SLAs engineering cannot meet.",
              "Missing DPAs for personal-data processing."]},
    {"name": "Open_Source_Licensing_Standards", "category": "Legal", "applies_to": "All third-party and open-source software", "priority": "High",
     "owner": "Legal Counsel", "tags": ["compliance", "general"],
     "statement": "Open-source usage MUST comply with licence obligations and be tracked.",
     "musts": ["Maintain an inventory of dependencies and licences (SBOM).",
               "Prohibit licences incompatible with the distribution model.",
               "Comply with attribution and copyleft obligations.",
               "Review new dependencies for licence risk."],
     "shoulds": ["Automate licence scanning in CI.",
                 "Prefer permissively licensed, well-maintained libraries."],
     "mays": ["Maintain an approved-licence allowlist."],
     "anti": ["Ignoring copyleft obligations.",
              "Unreviewed dependencies with unknown licences.",
              "No SBOM or licence inventory."]},
    {"name": "Pre_Sales_Engineering_Standards", "category": "Sales", "applies_to": "All technical pre-sales activities", "priority": "Medium",
     "owner": "Sales Engineer", "tags": ["general", "growth"],
     "statement": "Pre-sales activities MUST set accurate expectations and protect security and privacy commitments.",
     "musts": ["Scope proofs of concept with clear, time-boxed success criteria.",
               "Represent only capabilities that exist or are roadmap-committed.",
               "Involve Security/Privacy for questionnaire and RFP answers.",
               "Hand over full context to Customer Success on win."],
     "shoulds": ["Use standardised demo environments and scripts.",
                 "Capture field feedback for product."],
     "mays": ["Automate security-questionnaire responses from a knowledge base."],
     "anti": ["Over-promising unsupported capabilities.",
              "Unbounded, never-ending POCs.",
              "Inaccurate security or compliance claims."]},
    {"name": "Technology_Governance_Standards", "category": "Executive", "applies_to": "Technology strategy and investment", "priority": "High",
     "owner": "Chief Technology Officer", "tags": ["general", "release"],
     "statement": "Technology investment MUST align to strategy, manage risk, and be measured by outcomes.",
     "musts": ["Tie technology investment to business outcomes and OKRs.",
               "Retain executive ownership of security, privacy, and reliability risk.",
               "Govern major technology and vendor decisions.",
               "Report on delivery (DORA) and risk metrics."],
     "shoulds": ["Maintain a technology strategy and roadmap.",
                 "Balance innovation with reliability and cost."],
     "mays": ["Run periodic technology strategy reviews."],
     "anti": ["Strategy disconnected from execution.",
              "Underinvesting in security and reliability.",
              "Unbounded, ungoverned vendor spend."]},
]

# ---------------------------------------------------------------------------
# CHECKLISTS (18) - name, category, applies_to, owner, priority, audience, tags,
#                   primary[] (domain items merged with universal items)
# ---------------------------------------------------------------------------
CHECKLISTS = [
    {"name": "Production_Release_Checklist", "category": "Release", "applies_to": "All production releases",
     "owner": "Release Manager", "priority": "Critical", "audience": "Release/Eng/QA", "tags": ["release", "quality", "observability"],
     "primary": ["All required quality gates passed", "Rollback plan tested and ready",
                 "Release notes prepared and reviewed", "Feature flags configured and verified",
                 "Database migrations reviewed and reversible", "On-call coverage confirmed",
                 "Monitoring and alerts in place for new functionality", "Go/no-go decision recorded"]},
    {"name": "Security_Review_Checklist", "category": "Security", "applies_to": "All features touching sensitive flows",
     "owner": "Security Engineer", "priority": "Critical", "audience": "Security/Eng", "tags": ["security", "compliance"],
     "primary": ["Threat model completed and reviewed", "AuthN/AuthZ enforced server-side",
                 "Inputs validated; outputs encoded", "Secrets stored in a secrets manager",
                 "SAST/DAST/SCA pass with no open criticals", "Sensitive data encrypted in transit and at rest",
                 "Least-privilege access verified", "Security logging without sensitive data"]},
    {"name": "Architecture_Review_Checklist", "category": "Architecture", "applies_to": "Significant designs",
     "owner": "Enterprise Architect", "priority": "High", "audience": "Architects/Eng", "tags": ["cloud", "security", "observability"],
     "primary": ["Requirements and constraints documented", "Trade-offs captured in an ADR",
                 "Scalability and resilience addressed", "Failure modes and DR considered",
                 "Security and privacy designed in", "Observability designed in",
                 "Cost implications assessed", "Backward compatibility considered"]},
    {"name": "API_Review_Checklist", "category": "API", "applies_to": "All API changes",
     "owner": "API Architect", "priority": "High", "audience": "API/Eng", "tags": ["api", "backend", "security"],
     "primary": ["OpenAPI contract updated and validated", "Versioning and deprecation handled",
                 "Consistent error model (RFC 9457)", "Pagination/filtering conventions followed",
                 "AuthN/AuthZ defined per endpoint", "Rate limits and quotas defined",
                 "Backward compatibility verified", "Contract tests present and passing"]},
    {"name": "Code_Review_Checklist", "category": "Engineering", "applies_to": "All pull requests",
     "owner": "Principal Engineer", "priority": "High", "audience": "Engineers", "tags": ["general", "security", "quality"],
     "primary": ["Change is focused and understandable", "Tests cover new/changed behaviour",
                 "No secrets or credentials introduced", "Errors handled explicitly",
                 "No obvious security issues (injection, XSS)", "Naming and structure are clear",
                 "No unnecessary duplication", "Docs/comments updated where needed"]},
    {"name": "AI_Prompt_Review_Checklist", "category": "AI", "applies_to": "All prompt changes",
     "owner": "Prompt Engineer", "priority": "High", "audience": "AI Eng", "tags": ["ai", "eval"],
     "primary": ["Prompt versioned and tracked", "System/user instructions separated",
                 "Output schema defined and validated", "Injection mitigations in place",
                 "Evaluation suite run and passing", "Token cost and latency assessed",
                 "Untrusted content quarantined", "Fallback behaviour defined"]},
    {"name": "RAG_Evaluation_Checklist", "category": "AI", "applies_to": "All RAG pipelines",
     "owner": "RAG Engineer", "priority": "High", "audience": "AI Eng", "tags": ["ai", "data", "eval"],
     "primary": ["Tenant/permission filters enforced on retrieval", "Context relevance measured",
                 "Faithfulness/grounding measured (RAGAS)", "Index freshness within target",
                 "Chunking strategy validated", "Sources cited in answers",
                 "Retrieval latency within budget", "Eval datasets versioned"]},
    {"name": "Performance_Audit_Checklist", "category": "Performance", "applies_to": "User-facing features",
     "owner": "Performance Engineer", "priority": "High", "audience": "Eng/Perf", "tags": ["performance", "frontend", "observability"],
     "primary": ["Performance budgets defined and enforced", "Core Web Vitals within targets",
                 "Load/stress tests executed with realistic data", "p95/p99 latency within SLO",
                 "Critical rendering path optimised", "Caching and compression applied",
                 "No N+1 or unbounded queries", "Capacity headroom verified"]},
    {"name": "Accessibility_Audit_Checklist", "category": "Quality", "applies_to": "All UI",
     "owner": "Accessibility Specialist", "priority": "High", "audience": "Frontend/QA", "tags": ["accessibility", "frontend"],
     "primary": ["Keyboard operable with visible focus", "Screen-reader tested",
                 "Colour contrast meets WCAG 2.2 AA", "Target sizes meet minimums",
                 "Text alternatives for non-text content", "Forms have labels and error messaging",
                 "No keyboard traps", "Automated scan shows no critical issues"]},
    {"name": "Incident_Response_Checklist", "category": "Operations", "applies_to": "All incidents",
     "owner": "Site Reliability Engineer", "priority": "Critical", "audience": "On-call/SRE", "tags": ["observability", "security", "release"],
     "primary": ["Incident declared with severity", "Incident commander assigned",
                 "Stakeholders and status updates communicated", "Mitigation applied and verified",
                 "Customer impact assessed", "Timeline captured",
                 "Postmortem scheduled", "Remediation actions logged and owned"]},
    {"name": "GDPR_Readiness_Checklist", "category": "Privacy", "applies_to": "EU personal data",
     "owner": "Privacy Engineer", "priority": "Critical", "audience": "Privacy/Legal", "tags": ["privacy", "compliance", "security"],
     "primary": ["Lawful basis documented", "Records of processing (RoPA) maintained",
                 "Data-subject rights workflows operational", "Retention and deletion enforced",
                 "DPIA completed for high-risk processing", "Processor agreements (DPAs) in place",
                 "Cross-border transfer safeguards applied", "Breach notification process ready"]},
    {"name": "Stripe_Integration_Checklist", "category": "Finance", "applies_to": "Payment integrations",
     "owner": "Payments Engineer", "priority": "Critical", "audience": "Payments/Eng", "tags": ["finance", "security", "compliance"],
     "primary": ["Provider-hosted fields minimise PCI scope", "No raw card data stored",
                 "Webhook signatures verified", "Money operations idempotent",
                 "Reconciliation against ledger in place", "Failed-payment dunning handled",
                 "Subscription lifecycle (proration/upgrades) tested", "Test and live keys segregated"]},
    {"name": "SEO_AEO_GEO_Review_Checklist", "category": "Growth", "applies_to": "Public web pages",
     "owner": "SEO/AEO/GEO Specialist", "priority": "Medium", "audience": "Growth/Frontend", "tags": ["growth", "performance", "accessibility"],
     "primary": ["Pages crawlable and indexable", "Semantic HTML and metadata present",
                 "schema.org structured data implemented", "Core Web Vitals pass",
                 "Canonical URLs and sitemaps correct", "Content is clear and citable (AEO/GEO)",
                 "Internal linking is coherent", "No render-blocking that hides content"]},
    {"name": "Database_Migration_Checklist", "category": "Engineering", "applies_to": "Schema changes",
     "owner": "Database Architect", "priority": "High", "audience": "Eng/DBA", "tags": ["data", "backend"],
     "primary": ["Migration is expand-then-contract", "Rollback path defined and tested",
                 "Zero-downtime strategy verified", "Backups taken before migration",
                 "Performance impact assessed", "Data integrity constraints preserved",
                 "Migration tested on production-like data", "Monitoring during rollout"]},
    {"name": "Penetration_Test_Readiness_Checklist", "category": "Security", "applies_to": "Pre-pentest systems",
     "owner": "Security Engineer", "priority": "High", "audience": "Security", "tags": ["security", "compliance"],
     "primary": ["Scope and rules of engagement agreed", "Test environment representative of production",
                 "Known issues triaged beforehand", "Logging/monitoring enabled for the test",
                 "Emergency contacts defined", "Data handling and consent confirmed",
                 "Remediation SLA agreed", "Retest plan defined"]},
    {"name": "Data_Privacy_Checklist", "category": "Privacy", "applies_to": "Features handling personal data",
     "owner": "Privacy Engineer", "priority": "High", "audience": "Eng/Privacy", "tags": ["privacy", "security", "compliance"],
     "primary": ["Personal data identified and classified", "Data minimisation applied",
                 "Consent captured where required", "Encryption applied in transit and at rest",
                 "Retention and deletion configured", "Access restricted to least privilege",
                 "Third-party sharing documented", "Privacy notice updated if needed"]},
    {"name": "Observability_Readiness_Checklist", "category": "Operations", "applies_to": "New/changed services",
     "owner": "Observability Engineer", "priority": "High", "audience": "Eng/SRE", "tags": ["observability", "performance"],
     "primary": ["Structured logs with correlation IDs", "SLI metrics emitted",
                 "Distributed tracing instrumented", "Dashboards created for the service",
                 "Actionable alerts with runbooks", "No secrets/PII in telemetry",
                 "Retention and sampling configured", "Health/readiness endpoints present"]},
    {"name": "Disaster_Recovery_Checklist", "category": "Operations", "applies_to": "Critical systems",
     "owner": "Cloud Architect", "priority": "Critical", "audience": "SRE/Cloud", "tags": ["cloud", "observability", "security"],
     "primary": ["RPO/RTO targets defined", "Backups automated and encrypted",
                 "Restore tested within RTO", "Failover procedure documented and drilled",
                 "Cross-region/redundancy in place", "Runbooks current and accessible",
                 "Dependencies and data flows mapped", "Communication plan ready"]},
    {"name": "Contract_Review_Checklist", "category": "Legal", "applies_to": "Customer and vendor contracts",
     "owner": "Legal Counsel", "priority": "High", "audience": "Legal/Sales", "tags": ["compliance", "privacy", "general"],
     "primary": ["Approved template used or deviations reviewed", "DPA included where personal data is processed",
                 "SLAs achievable and agreed with engineering", "Liability and indemnity terms acceptable",
                 "Termination and renewal terms clear", "Security/privacy commitments consistent with product",
                 "IP and confidentiality terms correct", "Obligations recorded for tracking"]},
    {"name": "Data_Pipeline_Readiness_Checklist", "category": "Data", "applies_to": "New/changed data pipelines",
     "owner": "Data Engineer", "priority": "High", "audience": "Data/Eng", "tags": ["data", "backend", "observability"],
     "primary": ["Pipeline is idempotent and replayable", "Data-quality tests at ingestion and output",
                 "Schema changes are backward-compatible", "Lineage and catalogue updated",
                 "Monitoring and alerting in place", "Backfill and recovery procedure defined",
                 "Sensitive data classified and protected", "Freshness/SLA targets defined"]},
    {"name": "Data_Quality_Checklist", "category": "Data", "applies_to": "Datasets serving analytics/AI",
     "owner": "Data Engineer", "priority": "High", "audience": "Data/AI", "tags": ["data", "privacy"],
     "primary": ["Completeness checks pass", "Uniqueness/primary-key integrity verified",
                 "Validity/format constraints enforced", "Freshness within target",
                 "Consistency across sources reconciled", "Null/outlier thresholds within bounds",
                 "PII classified and masked where required", "Data dictionary documented"]},
    {"name": "Sales_POC_Readiness_Checklist", "category": "Sales", "applies_to": "Customer proofs of concept",
     "owner": "Sales Engineer", "priority": "Medium", "audience": "Sales/SE", "tags": ["general", "security"],
     "primary": ["Success criteria defined and agreed", "Scope and timeline bounded",
                 "Required access and data handling agreed", "Security/privacy questions answered accurately",
                 "Demoed capabilities exist or are roadmap-committed", "Environment provisioned with a reset plan",
                 "Stakeholders and decision process identified", "Handover-to-Customer-Success plan prepared"]},
    {"name": "Document_Quality_Gate_Checklist", "category": "Governance", "applies_to": "All framework documents",
     "owner": "Enterprise Architect", "priority": "Medium", "audience": "All authors", "tags": ["general"],
     "primary": ["Follows the specification structure", "Metadata/front matter complete",
                 "Owner and review frequency set", "Cross-references valid",
                 "Security/privacy/accessibility considerations addressed", "Version history updated",
                 "Renders correctly in Markdown", "Validated before publishing"]},
    {"name": "Quarterly_Technology_Review_Checklist", "category": "Executive", "applies_to": "Quarterly technology review",
     "owner": "Chief Technology Officer", "priority": "Medium", "audience": "Engineering leadership", "tags": ["general", "release"],
     "primary": ["OKR/business-outcome progress reviewed", "Delivery metrics (DORA) reviewed",
                 "Security and compliance posture reviewed", "Top technical risks reviewed and owned",
                 "Architecture and tech-debt roadmap reviewed", "Budget and cost variance reviewed",
                 "Talent and org health reviewed", "Action items assigned with owners"]},
]

# ---------------------------------------------------------------------------
# PLAYBOOKS (12) - name, category, owner, tags, objective, trigger,
#                  steps[], roles[]
# ---------------------------------------------------------------------------
PLAYBOOKS = [
    {"name": "Incident_Response_Playbook", "category": "Operations", "owner": "Site Reliability Engineer",
     "tags": ["observability", "security", "release"], "objective": "Restore service quickly and learn from production incidents.",
     "trigger": "An SLO breach, outage, or customer-impacting degradation is detected.",
     "roles": ["Incident Commander", "Communications Lead", "Operations Lead", "Scribe"],
     "steps": ["Detect and declare the incident with a severity level.",
               "Assign the Incident Commander and supporting roles.",
               "Stabilise: apply mitigation and verify impact reduction.",
               "Communicate status to stakeholders on a regular cadence.",
               "Diagnose root cause once service is stable.",
               "Resolve and confirm full recovery against SLIs.",
               "Run a blameless postmortem and log owned actions.",
               "Track remediation to closure."]},
    {"name": "Production_Deployment_Playbook", "category": "Release", "owner": "DevOps Engineer",
     "tags": ["release", "cloud", "observability"], "objective": "Deploy changes safely and predictably to production.",
     "trigger": "A release is approved and all quality gates have passed.",
     "roles": ["Release Manager", "DevOps Engineer", "On-call Engineer"],
     "steps": ["Confirm gate sign-offs and change record.",
               "Promote the tested artifact (no rebuild).",
               "Deploy progressively (canary/blue-green).",
               "Run automated smoke and health checks.",
               "Monitor SLIs and error rates during ramp.",
               "Promote to full traffic or roll back on regression.",
               "Publish release notes and close the change."]},
    {"name": "Rollback_Playbook", "category": "Release", "owner": "Release Manager",
     "tags": ["release", "observability"], "objective": "Reverse a problematic release quickly and safely.",
     "trigger": "Post-deploy verification fails or a regression is detected.",
     "roles": ["Release Manager", "On-call Engineer", "Incident Commander"],
     "steps": ["Decide to roll back using predefined criteria.",
               "Halt further rollout immediately.",
               "Revert to the last known-good artifact.",
               "Reverse or compensate incompatible data migrations.",
               "Verify recovery against SLIs and smoke tests.",
               "Communicate status and capture the timeline.",
               "Open a follow-up to fix forward."]},
    {"name": "Disaster_Recovery_Playbook", "category": "Operations", "owner": "Cloud Architect",
     "tags": ["cloud", "security", "observability"], "objective": "Recover critical systems within RPO/RTO after a major failure.",
     "trigger": "Loss of a region, data store, or critical dependency.",
     "roles": ["DR Lead", "Cloud Architect", "SRE", "Communications Lead"],
     "steps": ["Declare a disaster and activate the DR plan.",
               "Assess scope and select recovery strategy.",
               "Fail over to standby region/infrastructure.",
               "Restore data from tested backups.",
               "Validate integrity and functionality.",
               "Redirect traffic and confirm recovery.",
               "Communicate and document the event.",
               "Review and improve DR posture."]},
    {"name": "On_Call_Playbook", "category": "Operations", "owner": "Site Reliability Engineer",
     "tags": ["observability", "release"], "objective": "Enable effective, humane on-call coverage.",
     "trigger": "Start of an on-call rotation or a page.",
     "roles": ["On-call Engineer", "Secondary On-call", "Escalation Manager"],
     "steps": ["Confirm tooling, access, and runbook availability at handover.",
               "Acknowledge pages within the agreed SLA.",
               "Triage severity and follow the relevant runbook.",
               "Escalate per policy when needed.",
               "Mitigate and document actions taken.",
               "Hand over open issues with context.",
               "Feed recurring toil into automation backlog."]},
    {"name": "Security_Incident_Playbook", "category": "Security", "owner": "Security Engineer",
     "tags": ["security", "compliance", "observability"], "objective": "Contain and remediate security incidents.",
     "trigger": "Suspected or confirmed security compromise.",
     "roles": ["Security Incident Commander", "Security Engineer", "Legal", "Communications Lead"],
     "steps": ["Declare a security incident and preserve evidence.",
               "Contain affected systems and credentials.",
               "Eradicate the threat and rotate secrets.",
               "Recover services from a trusted state.",
               "Assess legal/regulatory notification duties.",
               "Notify per obligations and timelines.",
               "Conduct a postmortem and harden controls."]},
    {"name": "Data_Breach_Response_Playbook", "category": "Privacy", "owner": "Privacy Engineer",
     "tags": ["privacy", "compliance", "security"], "objective": "Respond lawfully and effectively to personal-data breaches.",
     "trigger": "Confirmed or suspected exposure of personal data.",
     "roles": ["DPO", "Privacy Engineer", "Security Engineer", "Legal"],
     "steps": ["Confirm and scope the breach.",
               "Contain and stop ongoing exposure.",
               "Assess affected data subjects and risk.",
               "Determine notification obligations (e.g., 72h under GDPR).",
               "Notify regulators and affected individuals as required.",
               "Document the breach and response.",
               "Remediate root cause and improve controls."]},
    {"name": "Performance_Tuning_Playbook", "category": "Performance", "owner": "Performance Engineer",
     "tags": ["performance", "observability"], "objective": "Diagnose and resolve performance regressions.",
     "trigger": "Latency, throughput, or CWV breach a budget or SLO.",
     "roles": ["Performance Engineer", "Backend Engineer", "Observability Engineer"],
     "steps": ["Reproduce and quantify the regression.",
               "Profile to locate the bottleneck.",
               "Form a hypothesis and a measurable target.",
               "Apply the smallest effective optimisation.",
               "Re-test under realistic load.",
               "Verify against budgets/SLOs and watch tails.",
               "Document findings and add regression guards."]},
    {"name": "Feature_Launch_Playbook", "category": "Product", "owner": "Product Manager",
     "tags": ["release", "growth"], "objective": "Launch features successfully with measurable outcomes.",
     "trigger": "A feature reaches launch readiness.",
     "roles": ["Product Manager", "Product Marketing", "Engineering", "Customer Success"],
     "steps": ["Confirm success metrics and instrumentation.",
               "Validate readiness across eng, docs, support, and GTM.",
               "Roll out progressively behind flags.",
               "Monitor adoption and quality signals.",
               "Enable sales/support and publish materials.",
               "Review outcomes against targets.",
               "Iterate or roll back based on data."]},
    {"name": "Database_Migration_Playbook", "category": "Engineering", "owner": "Database Architect",
     "tags": ["data", "backend", "release"], "objective": "Execute schema migrations safely with zero downtime.",
     "trigger": "A schema change is required for a release.",
     "roles": ["Database Architect", "Backend Engineer", "Release Manager"],
     "steps": ["Design an expand-then-contract migration.",
               "Review and test on production-like data.",
               "Back up before applying changes.",
               "Apply the expand phase (additive, backward-compatible).",
               "Deploy code that supports both schemas.",
               "Backfill and verify data integrity.",
               "Apply the contract phase after validation.",
               "Monitor and keep rollback ready."]},
    {"name": "Cost_Optimization_Playbook", "category": "Cloud", "owner": "Cloud Architect",
     "tags": ["cloud", "finance", "observability"], "objective": "Reduce cloud and operational cost without harming reliability.",
     "trigger": "Cost variance exceeds budget or a periodic review.",
     "roles": ["Cloud Architect", "Finance", "SRE"],
     "steps": ["Attribute costs via tagging and reports.",
               "Identify top cost drivers and waste.",
               "Right-size and remove idle resources.",
               "Apply commitments/discounts where stable.",
               "Optimise data transfer and storage tiers.",
               "Verify no reliability or performance regression.",
               "Track savings and set guardrails."]},
    {"name": "Customer_Escalation_Playbook", "category": "Customer Success", "owner": "Customer Success",
     "tags": ["general"], "objective": "Resolve high-impact customer escalations and protect the relationship.",
     "trigger": "A customer raises a critical or churn-risk issue.",
     "roles": ["Customer Success Manager", "Support", "Engineering", "Account Owner"],
     "steps": ["Acknowledge and set expectations quickly.",
               "Assess impact, urgency, and churn risk.",
               "Mobilise the right cross-functional responders.",
               "Communicate a plan and regular updates.",
               "Resolve and confirm customer satisfaction.",
               "Capture root cause and feedback for product.",
               "Follow up to rebuild trust."]},
]

# ---------------------------------------------------------------------------
# TEMPLATES (10) - name, purpose, sections[]
# ---------------------------------------------------------------------------
TEMPLATES = [
    {"name": "SKILLS_Template", "purpose": "Reusable scaffold for a specialist SKILLS.md document.",
     "sections": ["Title", "Purpose", "Mission", "Vision", "Role Overview", "Responsibilities", "Scope",
                  "Out of Scope", "Objectives", "Deliverables", "Decision Authority", "Industry Standards",
                  "Best Practices", "Anti-patterns", "Security/Privacy/Accessibility/Performance Considerations",
                  "Quality Gates", "Collaboration Matrix", "Review Checklist", "Definition of Done",
                  "KPIs", "Validation Checklist", "References", "Version History", "Metadata"]},
    {"name": "RULES_Template", "purpose": "Reusable scaffold for a RULES.md engineering standard.",
     "sections": ["Title", "Purpose", "Scope", "Out of Scope", "Rule Statement", "Rationale",
                  "Industry Standards", "Mandatory Requirements (MUST)", "Recommended (SHOULD)", "Optional (MAY)",
                  "Security/Privacy/Performance Requirements", "Anti-patterns", "Exceptions Process",
                  "Review Checklist", "Validation Checklist", "Definition of Compliance",
                  "Monitoring & Enforcement", "Metrics & KPIs", "References", "Version History", "Metadata"]},
    {"name": "CHECKLIST_Template", "purpose": "Reusable scaffold for a CHECKLIST.md quality gate.",
     "sections": ["Title", "Purpose", "Scope", "When to Use", "Prerequisites", "Roles & Responsibilities",
                  "Acceptance Criteria", "Quality Gate", "Primary Validation Checklist",
                  "Security/Privacy/Accessibility/Performance Validation", "Definition of Pass/Fail",
                  "Evidence Required", "Sign-off Matrix", "Metrics", "References", "Metadata"]},
    {"name": "PLAYBOOK_Template", "purpose": "Reusable scaffold for an operational PLAYBOOK.md.",
     "sections": ["Title", "Purpose", "Objective", "Trigger", "Roles", "Preconditions", "Procedure",
                  "Decision Points", "Communication Plan", "Rollback/Recovery", "Post-Procedure Review",
                  "Metrics", "References", "Metadata"]},
    {"name": "KNOWLEDGE_Template", "purpose": "Reusable scaffold for a KNOWLEDGE.md reference article.",
     "sections": ["Title", "Summary", "Context", "Key Concepts", "Guidance", "Examples",
                  "Pitfalls", "Related Documents", "References", "Metadata"]},
    {"name": "ADR_Template", "purpose": "Architecture Decision Record capturing a significant decision.",
     "sections": ["Title", "Status", "Context", "Decision", "Alternatives Considered",
                  "Consequences", "Compliance/Security Impact", "References", "Metadata"]},
    {"name": "PRD_Template", "purpose": "Product Requirements Document for a feature or initiative.",
     "sections": ["Title", "Problem Statement", "Goals & Non-Goals", "Personas", "User Stories",
                  "Requirements", "Success Metrics", "Risks", "Dependencies", "Acceptance Criteria", "Metadata"]},
    {"name": "RFC_Template", "purpose": "Request for Comments proposing a technical change.",
     "sections": ["Title", "Summary", "Motivation", "Detailed Design", "Trade-offs", "Alternatives",
                  "Security/Privacy Considerations", "Rollout Plan", "Open Questions", "References", "Metadata"]},
    {"name": "Postmortem_Template", "purpose": "Blameless incident postmortem.",
     "sections": ["Title", "Summary", "Impact", "Timeline", "Root Cause", "Contributing Factors",
                  "What Went Well", "What Went Poorly", "Action Items", "Lessons Learned", "Metadata"]},
    {"name": "Runbook_Template", "purpose": "Operational runbook for a recurring task or alert.",
     "sections": ["Title", "Purpose", "Scope", "Preconditions", "Procedure", "Verification",
                  "Rollback", "Escalation", "Related Alerts", "References", "Metadata"]},
]

# ---------------------------------------------------------------------------
# KNOWLEDGE (6) - name, summary, concepts[], guidance[], pitfalls[]
# ---------------------------------------------------------------------------
KNOWLEDGE = [
    {"name": "Engineering_Principles", "summary": "The cross-cutting principles every ASFE artefact must uphold.",
     "concepts": ["Security and Privacy by Design", "Accessibility by Default", "Cloud Native and API First",
                  "Observability First", "Zero Trust and Least Privilege", "Documentation and Infrastructure as Code"],
     "guidance": ["Apply principles as defaults, not exceptions.",
                  "Make principles measurable via gates and KPIs.",
                  "Resolve conflicts in favour of security, privacy, and safety."],
     "pitfalls": ["Treating principles as aspirational slogans.",
                  "Bolting on security/accessibility after build.",
                  "Principles without enforcement."]},
    {"name": "Glossary", "summary": "Definitions of common ASFE terms, metrics, and acronyms.",
     "concepts": ["SLI/SLO/Error Budget", "ARR/MRR/NRR/Churn", "RPO/RTO", "DORA metrics",
                  "WCAG/ARIA", "RAG/Embeddings/Grounding", "SBOM/SCA/SAST/DAST"],
     "guidance": ["Use consistent terminology across documents.",
                  "Link first use of a term to this glossary.",
                  "Keep definitions vendor-neutral."],
     "pitfalls": ["Overloaded terms with conflicting meanings.",
                  "Undefined acronyms in critical docs."]},
    {"name": "Technology_Radar", "summary": "Guidance on adopting, trialling, or retiring technologies.",
     "concepts": ["Adopt / Trial / Assess / Hold rings", "Techniques, Tools, Platforms, Languages & Frameworks",
                  "Fitness functions", "Total cost of ownership"],
     "guidance": ["Evaluate against principles and standards before adoption.",
                  "Prefer boring, well-supported technology for core systems.",
                  "Document decisions as ADRs."],
     "pitfalls": ["Resume-driven technology choices.",
                  "Adopting unproven tech for critical paths.",
                  "No exit strategy for retired tech."]},
    {"name": "Standards_Index", "summary": "Index of external standards referenced across ASFE.",
     "concepts": ["Security (OWASP, NIST, CIS, ISO 27001, SOC 2)", "Privacy (GDPR, ISO 27701)",
                  "Accessibility (WCAG 2.2, ARIA, EN 301 549)", "API (OpenAPI, OAuth 2.1, RFC 9457)",
                  "AI (NIST AI RMF, ISO 42001, OWASP LLM Top 10, RAGAS, DeepEval)",
                  "Delivery (Twelve-Factor, SemVer, DORA, OpenTelemetry)"],
     "guidance": ["Map each document to applicable standards.",
                  "Track standard versions and review on update.",
                  "Prefer official primary sources."],
     "pitfalls": ["Citing outdated standard versions.",
                  "Claiming compliance without evidence."]},
    {"name": "Security_Reference_Architecture", "summary": "Baseline secure architecture patterns for SaaS.",
     "concepts": ["Zero-trust network and identity", "Defense in depth", "Secrets and key management",
                  "Tenant isolation", "Secure SDLC and supply chain", "Encryption everywhere"],
     "guidance": ["Default deny; segment and isolate by tenant.",
                  "Centralise identity, secrets, and key management.",
                  "Automate security gates across the SDLC."],
     "pitfalls": ["Flat networks and shared credentials.",
                  "Implicit trust between services.",
                  "Manual, late security reviews."]},
    {"name": "AI_Engineering_Reference", "summary": "Reference patterns for building safe, evaluated AI features.",
     "concepts": ["Model gateway and routing", "Guardrails (input/output/behaviour)", "RAG grounding and citations",
                  "Evaluation and regression gates", "Prompt versioning", "Cost and latency observability"],
     "guidance": ["Constrain and validate outputs; never trust raw generations.",
                  "Gate AI changes on automated evaluation.",
                  "Ground answers with access-controlled retrieval and citations."],
     "pitfalls": ["Unbounded prompt injection.",
                  "No evaluation before shipping AI changes.",
                  "Sending sensitive data to models without controls."]},
]
